import type { RacebookEditionService, RacebookLocale, RacebookViewModel } from "../model";

export function getRacebookAction(context:string):string|undefined{if(context==="official")return "official_website_opened";if(context==="instagram")return "instagram_opened";if(context==="facebook")return "facebook_opened";if(context==="emergency")return "emergency_call_started";if(context.startsWith("service_directions_"))return "service_directions";if(context.startsWith("service_website_"))return "service_website";if(context.startsWith("service_phone_"))return undefined;if(context.startsWith("access_")||context==="bib"||context==="hero_location")return "map_opened";return "external_action";}
export function getRacebookActionContext(context:string,services:ReadonlyArray<Pick<RacebookEditionService,"id"|"serviceType">>){if(!context.startsWith("service_"))return context;return services.find(service=>context.endsWith(`_${service.id}`))?.serviceType??context;}
export function formatRacebookDate(value:string|null|undefined,locale:RacebookLocale,short=false){if(!value)return null;const parsed=new Date(/^\d{4}-\d{2}-\d{2}$/.test(value)?`${value}T12:00:00`:value);if(Number.isNaN(parsed.getTime()))return value;return parsed.toLocaleDateString(locale==="fr"?"fr-FR":"en-US",{...(short?{weekday:"short" as const}:null),day:"numeric",month:"short",...(short?null:{year:"numeric" as const})});}
export function formatRacebookDateRange(start:string|null|undefined,end:string|null|undefined,locale:RacebookLocale){const left=formatRacebookDate(start,locale),right=formatRacebookDate(end,locale);if(!left)return right;if(!right||left===right)return left;return `${left} – ${right}`;}
function distanceKm(aLat:number,aLng:number,bLat:number,bLng:number){const rad=(v:number)=>v*Math.PI/180,dLat=rad(bLat-aLat),dLng=rad(bLng-aLng),h=Math.sin(dLat/2)**2+Math.cos(rad(aLat))*Math.cos(rad(bLat))*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
export function resolveServicePresentation(service:RacebookEditionService,origin:{lat:number|null|undefined;lng:number|null|undefined}){return {...service,distanceKm:origin.lat!=null&&origin.lng!=null&&service.latitude!=null&&service.longitude!=null?distanceKm(origin.lat,origin.lng,service.latitude,service.longitude):null,directionsUrl:service.googleMapsUrl??(service.latitude!=null&&service.longitude!=null?`https://www.google.com/maps/dir/?api=1&destination=${service.latitude},${service.longitude}`:null)};}
export function reconcileTab<T extends string>(requested:T,available:readonly T[],fallback:T){return available.includes(requested)?requested:(available[0]??fallback);}
export function visibleSponsorIndexes(count:number,index:number,reducedMotion:boolean){if(count<=0)return [];if(reducedMotion)return Array.from({length:count},(_,i)=>i);return [Math.max(0,index%count)];}
export function countVisiblePrimaryTabs(model:RacebookViewModel){const hasServices=model.data.editionServices.length>0||Object.values(model.data.legacyServices).some(Boolean);return 1+Number(model.modules.equipment)+Number(model.modules.bibPickup)+Number(model.modules.access)+Number(model.modules.services&&hasServices);}
