import { StyleSheet } from 'react-native';
import { Colors } from '../../constants/colors';

export const inputStyles = StyleSheet.create({
  input: {
    backgroundColor: Colors.surface,
    color: Colors.textPrimary,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    flex: 1,
  },
});

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  content: { padding: 20, paddingBottom: 48 },
  highlightsSection: {
    marginBottom: 24,
  },
  highlightsAccordionHeader: { marginBottom: 0 },
  highlightsSubtitle: { color: Colors.textSecondary, fontSize: 12, lineHeight: 17, marginBottom: 10 },
  highlightsHeroRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 8,
  },
  highlightsHeroPrimary: {
    flex: 1,
    justifyContent: 'center',
  },
  highlightsHeroValue: { color: Colors.brandPrimary, fontSize: 28, fontWeight: '800', lineHeight: 32 },
  highlightsHeroLabel: { color: Colors.textSecondary, fontSize: 12, fontWeight: '600', marginTop: 3 },
  highlightsHeroSecondary: {
    minWidth: 124,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.brandBorder,
    backgroundColor: Colors.brandSurface,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  highlightsHeroSecondaryValue: { color: Colors.brandPrimary, fontSize: 22, fontWeight: '800', lineHeight: 24 },
  highlightsHeroSecondaryLabel: { color: Colors.textPrimary, fontSize: 12, fontWeight: '700', marginTop: 4 },
  highlightsHeroSecondaryMeta: { color: Colors.textSecondary, fontSize: 11, marginTop: 2 },
  highlightMetricsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 8 },
  highlightMetricChip: {
    flexGrow: 1,
    backgroundColor: Colors.surfaceSecondary,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 10,
    paddingVertical: 8,
    minWidth: '30%',
  },
  highlightMetricChipLabel: { color: Colors.textMuted, fontSize: 11, fontWeight: '700' },
  highlightMetricChipValue: { color: Colors.textPrimary, fontSize: 13, fontWeight: '700', marginTop: 3 },
  highlightBreakdownSection: { marginTop: 10 },
  highlightsInlinePrimaryBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colors.brandBorder,
    backgroundColor: Colors.brandSurface,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  highlightsInlinePrimaryValue: {
    color: Colors.brandPrimary,
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 16,
  },
  highlightsInlinePrimaryLabel: {
    color: Colors.textSecondary,
    fontSize: 10,
    fontWeight: '700',
  },
  highlightsCollapsedRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: 6,
    marginBottom: 8,
  },
  highlightsCollapsedLead: { flex: 1 },
  highlightsCollapsedLeadValue: { color: Colors.brandPrimary, fontSize: 24, fontWeight: '800', lineHeight: 28 },
  highlightsCollapsedLeadLabel: { color: Colors.textSecondary, fontSize: 12, fontWeight: '600', marginTop: 2 },
  highlightsCollapsedProductBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colors.brandBorder,
    backgroundColor: Colors.brandSurface,
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 88,
  },
  highlightsCollapsedProductValue: { color: Colors.brandPrimary, fontSize: 18, fontWeight: '800', lineHeight: 20 },
  highlightsCollapsedProductLabel: { color: Colors.textPrimary, fontSize: 11, fontWeight: '700', marginTop: 2 },
  highlightBreakdownLabel: { color: Colors.textSecondary, fontSize: 12, fontWeight: '700', marginBottom: 8 },
  highlightBreakdownRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  highlightBreakdownChip: {
    backgroundColor: Colors.brandSurface,
    color: Colors.brandPrimary,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colors.brandBorder,
    paddingHorizontal: 10,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: '700',
  },
  highlightEmptyText: { color: Colors.textMuted, fontSize: 12, fontStyle: 'italic', marginTop: 10 },
  sectionAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: 44,
    marginHorizontal: -6,
    marginBottom: 8,
    paddingHorizontal: 6,
    paddingVertical: 8,
  },
  sectionAccordionHeaderSpaced: { marginTop: 16 },
  sectionAccordionHeaderCollapsed: {
    marginBottom: 4,
    paddingVertical: 6,
  },
  sectionAccordionHeaderContent: { flex: 1, marginRight: 10 },
  sectionAccordionTitleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
  },
  sectionAccordionTitle: { marginBottom: 0 },
  sectionSummaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 4,
  },
  sectionSummaryRowInline: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
  },
  sectionSummaryChip: {
    backgroundColor: Colors.surfaceSecondary,
    color: Colors.textSecondary,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: '600',
  },
  sectionSummaryChipInline: {
    backgroundColor: Colors.surfaceSecondary,
    color: Colors.textSecondary,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 11,
    fontWeight: '600',
  },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  sectionTitle: { fontSize: 16, fontWeight: '700', color: Colors.brandPrimary, marginBottom: 12 },
  label: { fontSize: 13, color: Colors.textSecondary, marginBottom: 6, marginTop: 4 },
  textInput: {
    backgroundColor: Colors.surface,
    color: Colors.textPrimary,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 4,
  },
  stationInput: {
    backgroundColor: Colors.surfaceSecondary,
    color: Colors.textPrimary,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    marginBottom: 4,
  },
  row: { flexDirection: 'row', marginBottom: 4 },
  rowItem: { flex: 1 },
  toggleRow: {
    flexDirection: 'row',
    backgroundColor: Colors.surfaceSecondary,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: 4,
    marginBottom: 12,
  },
  toggleBtn: { flex: 1, paddingVertical: 10, alignItems: 'center', borderRadius: 8 },
  toggleBtnActive: { backgroundColor: Colors.surface },
  toggleBtnText: { color: Colors.textMuted, fontSize: 14, fontWeight: '600' },
  toggleBtnTextActive: { color: Colors.textPrimary, fontWeight: '600' },
  waterBagRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginBottom: 4 },
  waterBagBtn: {
    backgroundColor: Colors.surface,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  waterBagBtnActive: { backgroundColor: Colors.brandPrimary, borderColor: Colors.brandPrimary },
  waterBagBtnText: { color: Colors.textSecondary, fontSize: 14, fontWeight: '500' },
  waterBagBtnTextActive: { color: Colors.textOnBrand },
  sectionActions: { flexDirection: 'row', gap: 6, flexWrap: 'wrap', justifyContent: 'flex-end' },
  fillBtn: {
    backgroundColor: 'transparent',
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#7C3AED',
  },
  fillBtnText: { color: '#7C3AED', fontSize: 13, fontWeight: '600' },
  addBtn: {
    backgroundColor: 'transparent',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: Colors.brandLight,
  },
  addBtnText: { color: Colors.brandLight, fontSize: 14, fontWeight: '600' },
  emptyText: { color: Colors.textMuted, fontSize: 14, fontStyle: 'italic', textAlign: 'center', paddingVertical: 16 },
  stationCard: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 3,
  },
  stationCardCollapsedGreen: { backgroundColor: '#F1F8EC' },
  stationCardCollapsedOrange: { backgroundColor: '#FFF4E8' },
  stationCardCollapsedRed: { backgroundColor: '#FDECEC' },
  stationCardSystem: { backgroundColor: Colors.surfaceSecondary },
  stationHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  stationHeaderRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 12 },
  stationIcon: { fontSize: 16, marginRight: 8 },
  stationName: { flex: 1, color: Colors.textPrimary, fontWeight: '600', fontSize: 15 },
  stationPauseBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colors.brandBorder,
    backgroundColor: Colors.brandSurface,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 8,
  },
  stationPauseText: { color: Colors.brandPrimary, fontSize: 11, fontWeight: '700' },
  stationKm: { color: Colors.textSecondary, fontSize: 13 },
  chevron: { color: Colors.textMuted, fontSize: 12, marginLeft: 8 },
  cardDivider: { height: 1, backgroundColor: Colors.border },
  headerIconBtn: { padding: 6, borderRadius: 6, marginLeft: 2 },
  separator: { flexDirection: 'row', alignItems: 'center', marginVertical: 4, paddingHorizontal: 8 },
  separatorLine: { flex: 1, height: 1, backgroundColor: Colors.border },
  separatorText: { marginHorizontal: 10, color: Colors.textMuted, fontSize: 12 },
  separatorChevron: { color: Colors.textMuted, fontSize: 12, marginRight: 8 },
  sectionStationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
    marginBottom: 8,
    paddingHorizontal: 4,
    gap: 8,
  },
  sectionStationLine: { flex: 1, height: 1, backgroundColor: Colors.border },
  sectionStationLabel: { color: Colors.textPrimary, fontSize: 13, fontWeight: '700', maxWidth: '50%' },
  sectionStationKm: { color: Colors.textMuted, fontSize: 12, fontWeight: '600' },
  sectionViewCard: {
    marginBottom: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  sectionViewHeader: { marginBottom: 8 },
  sectionViewTitle: { color: Colors.textPrimary, fontSize: 14, fontWeight: '700' },
  sectionViewMeta: { color: Colors.textSecondary, fontSize: 12, marginTop: 2 },
  profileCard: {
    marginBottom: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  profileSectionBlock: { marginBottom: 14 },
  profileSectionHeader: { paddingHorizontal: 4, marginBottom: 10 },
  profileHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 10 },
  profileHeaderText: { flex: 1 },
  profileTitle: { color: Colors.textPrimary, fontSize: 14, fontWeight: '700' },
  profileMeta: { color: Colors.textSecondary, fontSize: 12, marginTop: 2 },
  profileEmptyText: { color: Colors.textMuted, fontSize: 13, fontStyle: 'italic', marginBottom: 10 },
  profilePaceWrap: {
    width: 148,
    alignItems: 'stretch',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.brandBorder,
    backgroundColor: Colors.brandSurface,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  profilePaceLabel: { color: Colors.brandPrimary, fontSize: 11, fontWeight: '700', textAlign: 'center', marginBottom: 4 },
  profilePaceControlRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  profilePaceStepBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.brandBorder,
    backgroundColor: Colors.brandSurface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profilePaceStepBtnText: { color: Colors.brandPrimary, fontSize: 16, fontWeight: '700' },
  profilePaceInput: {
    flex: 1,
    minWidth: 62,
    borderRadius: 8,
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    color: Colors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    paddingHorizontal: 6,
    paddingVertical: 7,
  },
  profilePaceHint: { color: Colors.textMuted, fontSize: 10, marginTop: 4, textAlign: 'center' },
  profileChart: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
    paddingVertical: 6,
    paddingHorizontal: 2,
    marginBottom: 10,
    borderRadius: 10,
    backgroundColor: Colors.surfaceSecondary,
  },
  profileChartEmpty: {
    height: 56,
    borderRadius: 10,
    backgroundColor: Colors.surfaceSecondary,
    marginBottom: 10,
  },
  profileChartBar: {
    flex: 1,
    borderRadius: 999,
    backgroundColor: Colors.brandPrimary,
    opacity: 0.85,
  },
  profilePresetRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  profilePresetBtn: {
    flex: 1,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surfaceSecondary,
    paddingVertical: 8,
    alignItems: 'center',
  },
  profilePresetBtnText: { color: Colors.textPrimary, fontSize: 12, fontWeight: '700' },
  profileSegmentsList: { gap: 8 },
  profileSegmentRow: {
    flexDirection: 'row',
    gap: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surfaceSecondary,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  profileSegmentInfo: { flex: 1 },
  profileSegmentLabel: { color: Colors.textPrimary, fontSize: 13, fontWeight: '700' },
  profileSegmentMeta: { color: Colors.textSecondary, fontSize: 12, marginTop: 3 },
  profileSegmentTimeLabel: { color: Colors.textMuted, fontSize: 11, fontWeight: '600', marginTop: 8 },
  profileSegmentTime: { color: Colors.brandPrimary, fontSize: 24, fontWeight: '800', marginTop: 2, lineHeight: 28 },
  profileSegmentInputWrap: { width: 90, alignItems: 'stretch' },
  profileSegmentInputLabel: { color: Colors.textMuted, fontSize: 11, fontWeight: '600', marginBottom: 4, textAlign: 'center' },
  profileSegmentInput: {
    backgroundColor: Colors.surface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    color: Colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  profileSegmentInputHint: { color: Colors.textMuted, fontSize: 10, marginTop: 4, textAlign: 'center' },
  profileMetricsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  profileMetricPill: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surfaceSecondary,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  profileMetricPillText: { color: Colors.textSecondary, fontSize: 12, fontWeight: '700' },
  profileSegmentControls: { marginTop: 2 },
  profileSegmentActions: { gap: 8 },
  profileActionBtn: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surfaceSecondary,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileActionBtnDisabled: { opacity: 0.45 },
  profileActionBtnText: { color: Colors.textPrimary, fontSize: 12, fontWeight: '700', textAlign: 'center' },
  profileDeleteBtn: { borderColor: '#F9A8A8', backgroundColor: '#FEF2F2' },
  profileDeleteBtnText: { color: '#DC2626', fontSize: 12, fontWeight: '700', textAlign: 'center' },
  sectionTimelineCard: {
    marginTop: 6,
    marginBottom: 10,
    marginHorizontal: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.surface,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  sectionTimelineRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  sectionTimelineRowLast: { borderBottomWidth: 0 },
  sectionTimelineTime: { width: 56, color: Colors.textSecondary, fontSize: 12, fontWeight: '700' },
  sectionTimelineInfo: { flex: 1 },
  sectionTimelineLabel: { color: Colors.textPrimary, fontSize: 13, fontWeight: '600' },
  sectionTimelineDetail: { color: Colors.textMuted, fontSize: 12, marginTop: 1 },
  sectionTimelineEmpty: { color: Colors.textMuted, fontSize: 13, fontStyle: 'italic', paddingVertical: 4 },
  collapsedGaugeRow: { paddingHorizontal: 10, paddingBottom: 10 },
  editModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  editModalCard: { backgroundColor: Colors.surface, borderRadius: 16, padding: 24, width: '100%' },
  editModalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 },
  editModalTitle: { fontSize: 17, fontWeight: '700', color: Colors.textPrimary },
  stationOrderButtons: { flexDirection: 'row', gap: 4, marginRight: 8 },
  orderBtn: {
    backgroundColor: Colors.surfaceSecondary,
    borderWidth: 1,
    borderColor: Colors.border,
    width: 28,
    height: 28,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  orderBtnDisabled: { opacity: 0.3 },
  orderBtnText: { color: Colors.textSecondary, fontSize: 14 },
  stationIndex: { flex: 1, color: Colors.textSecondary, fontSize: 13, fontWeight: '600' },
  stationSystemLabel: { flex: 1, color: Colors.brandPrimary, fontSize: 14, fontWeight: '700' },
  stationLockedKm: { color: Colors.textSecondary, fontSize: 14, fontWeight: '500', marginBottom: 4 },
  arriveeNote: { color: Colors.textMuted, fontSize: 13, fontStyle: 'italic', marginTop: 4 },
  removeBtn: { width: 28, height: 28, borderRadius: 14, backgroundColor: Colors.dangerSurface, justifyContent: 'center', alignItems: 'center' },
  removeBtnText: { color: Colors.danger, fontSize: 13, fontWeight: '700' },
  gaugesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 14,
    paddingHorizontal: 8,
    gap: 8,
  },
  gaugesRowCompact: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 2,
    paddingHorizontal: 0,
    gap: 6,
  },
  gaugeCard: { flex: 1, alignItems: 'center' },
  gaugeLabel: { fontSize: 10, color: Colors.textSecondary, marginBottom: 8, textAlign: 'center', fontWeight: '700' },
  gaugeValue: { fontSize: 10, color: Colors.textPrimary, marginTop: 6, textAlign: 'center', fontWeight: '700' },
  suppliesSection: { borderTopWidth: 1, borderTopColor: Colors.border, paddingTop: 10, paddingHorizontal: 14, paddingBottom: 6 },
  suppliesHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  suppliesLabel: { color: Colors.textSecondary, fontSize: 13, fontWeight: '600' },
  suppliesAddBtn: { color: Colors.brandPrimary, fontSize: 13, fontWeight: '600' },
  suppliesEmpty: { color: Colors.textMuted, fontSize: 13, fontStyle: 'italic' },
  supplyRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6, gap: 8 },
  supplyInfo: { flex: 1 },
  supplyName: { color: Colors.textPrimary, fontSize: 14, fontWeight: '600' },
  supplyType: { color: Colors.textMuted, fontSize: 11, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5 },
  supplyMeta: { color: Colors.textSecondary, fontSize: 12, marginTop: 2 },
  supplyControls: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  qtyBtn: {
    backgroundColor: Colors.surface,
    borderWidth: 1,
    borderColor: Colors.border,
    width: 28,
    height: 28,
    borderRadius: 6,
    justifyContent: 'center',
    alignItems: 'center',
  },
  qtyBtnDisabled: { opacity: 0.3 },
  qtyBtnText: { color: Colors.textPrimary, fontSize: 16, fontWeight: '600' },
  qtyText: { color: Colors.textPrimary, fontWeight: '700', minWidth: 24, textAlign: 'center', fontSize: 15 },
  removeSupplyBtn: { paddingLeft: 8 },
  removeSupplyText: { color: Colors.danger, fontSize: 18 },
  saveButton: { backgroundColor: Colors.brandPrimary, borderRadius: 12, paddingVertical: 18, alignItems: 'center', marginTop: 32 },
  saveButtonDisabled: { opacity: 0.6 },
  saveButtonText: { color: Colors.textOnBrand, fontSize: 17, fontWeight: '700' },
  saveSpacer: { height: 88 },
  floatingSaveButton: {
    position: 'absolute',
    right: 20,
    bottom: 24,
    backgroundColor: Colors.brandPrimary,
    borderRadius: 999,
    width: 56,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  modalWrapper: { flex: 1, justifyContent: 'flex-end' },
  modalOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.5)' },
  pickerSheet: { backgroundColor: Colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 40, maxHeight: '80%' },
  pickerHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  pickerTitle: { fontSize: 17, fontWeight: '700', color: Colors.textPrimary },
  pickerCloseBtn: { width: 32, height: 32, borderRadius: 16, backgroundColor: Colors.surfaceSecondary, justifyContent: 'center', alignItems: 'center' },
  pickerCloseText: { color: Colors.textSecondary, fontSize: 14, fontWeight: '700' },
  pickerSearchInput: {
    backgroundColor: Colors.surfaceSecondary,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: Colors.textPrimary,
    marginBottom: 12,
  },
  pickerSectionTitle: {
    color: Colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 12,
    marginBottom: 6,
  },
  pickerEmpty: { color: Colors.textMuted, fontSize: 14, fontStyle: 'italic', textAlign: 'center', paddingVertical: 12 },
  pickerRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: Colors.border },
  pickerRowInfo: { flex: 1, marginRight: 12 },
  pickerRowName: { color: Colors.textPrimary, fontSize: 14, fontWeight: '600' },
  pickerRowType: { color: Colors.textMuted, fontSize: 11, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5, marginTop: 1 },
  pickerAddBtn: { backgroundColor: 'transparent', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, borderWidth: 1.5, borderColor: Colors.brandPrimary },
  pickerAddBtnDone: { borderColor: Colors.brandPrimary, backgroundColor: Colors.brandPrimary },
  pickerAddBtnText: { color: Colors.brandPrimary, fontSize: 12, fontWeight: '600' },
  pickerAddBtnTextDone: { color: Colors.textOnBrand },
});
