import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { withSecurityHeaders } from "../../../../../../lib/http";
import { jsonError, loadRaceForOrganizer, requireOrganizerAuth, serviceHeaders, uuidParamSchema } from "../../../../../../lib/organizer";
import { isOrganizerRaceModuleSelected } from "../../../../../../lib/organizer-module-settings";
import { mapRaceAwardPayload, raceAwardsPayloadSchema } from "../../../../../../lib/organizer-structured-content";
const row=z.object({id:z.string().uuid(),category_key:z.string(),category_label:z.string(),audience:z.string(),place_from:z.number(),place_to:z.number(),podium_time:z.string(),podium_location:z.string().nullable(),reward_note:z.string().nullable(),order_index:z.number()});
const map=(r:z.infer<typeof row>)=>({id:r.id,categoryKey:r.category_key,categoryLabel:r.category_label,audience:r.audience,placeFrom:r.place_from,placeTo:r.place_to,podiumTime:r.podium_time.slice(0,5),podiumLocation:r.podium_location,rewardNote:r.reward_note});
async function auth(request:NextRequest,id:string){const a=await requireOrganizerAuth(request);if("error"in a)return a;const race=await loadRaceForOrganizer(a.serviceConfig,a.user,id);if("error"in race)return race;if(!race.edition_id||!(await isOrganizerRaceModuleSelected(a.serviceConfig,race.edition_id,id,"awards")))return{error:jsonError("Activez la section Podiums pour modifier son brouillon.",403)};return a}
async function load(config:Parameters<typeof serviceHeaders>[0],id:string){const r=await fetch(`${config.supabaseUrl}/rest/v1/race_awards?race_id=eq.${id}&select=id,category_key,category_label,audience,place_from,place_to,podium_time,podium_location,reward_note,order_index&order=podium_time.asc,order_index.asc`,{headers:serviceHeaders(config,""),cache:"no-store"});if(!r.ok)throw new Error();return z.array(row).parse(await r.json()).map(map)}
export async function GET(req:NextRequest,{params}:{params:{id?:string}}){const p=uuidParamSchema.safeParse(params);if(!p.success)return jsonError("Invalid race id.",400);const a=await auth(req,p.data.id);if("error"in a)return a.error;try{return withSecurityHeaders(NextResponse.json({awards:await load(a.serviceConfig,p.data.id)}))}catch{return jsonError("Unable to load awards.",502)}}
export async function PUT(req:NextRequest,{params}:{params:{id?:string}}){const p=uuidParamSchema.safeParse(params);if(!p.success)return jsonError("Invalid race id.",400);const a=await auth(req,p.data.id);if("error"in a)return a.error;const b=raceAwardsPayloadSchema.safeParse(await req.json().catch(()=>null));if(!b.success)return jsonError(b.error.issues[0]?.message??"Invalid awards.",400);const r=await fetch(`${a.serviceConfig.supabaseUrl}/rest/v1/rpc/replace_race_awards`,{method:"POST",headers:serviceHeaders(a.serviceConfig),body:JSON.stringify({p_race_id:p.data.id,p_items:b.data.awards.map(mapRaceAwardPayload)}),cache:"no-store"});if(!r.ok)return jsonError("Unable to save awards.",502);return withSecurityHeaders(NextResponse.json({awards:z.array(row).parse(await r.json()).map(map)}))}
