"use client";

import React from "react";
import { usePathname } from "next/navigation";

import { translations } from "../locales";
import type { Locale } from "../locales/types";
import { localeToOgLocale, SITE_URL } from "./seo";

const upsertMeta = (
  type: "name" | "property",
  key: string,
  content: string,
): void => {
  const selector = `meta[${type}="${key}"]`;
  let element = document.head.querySelector<HTMLMetaElement>(selector);

  if (!element) {
    element = document.createElement("meta");
    element.setAttribute(type, key);
    document.head.appendChild(element);
  }

  element.content = content;
};

const upsertLink = (rel: string, href: string): void => {
  const selector = `link[rel="${rel}"]`;
  let element = document.head.querySelector<HTMLLinkElement>(selector);

  if (!element) {
    element = document.createElement("link");
    element.rel = rel;
    document.head.appendChild(element);
  }

  element.href = href;
};

type RouteMeta = {
  locale: Locale;
  title: string;
  description: string;
  canonicalPath: string;
};

const getRouteMeta = (pathname: string): RouteMeta | undefined => {
  switch (pathname) {
    case "/partenaires":
      return {
        locale: "fr",
        title: translations.fr.partners.meta.title,
        description: translations.fr.partners.meta.description,
        canonicalPath: "/partenaires",
      };
    case "/en/partners":
      return {
        locale: "en",
        title: translations.en.partners.meta.title,
        description: translations.en.partners.meta.description,
        canonicalPath: "/en/partners",
      };
    case "/links":
      return {
        locale: "fr",
        title: translations.fr.links.meta.title,
        description: translations.fr.links.meta.description,
        canonicalPath: "/links",
      };
    case "/en/links":
      return {
        locale: "en",
        title: translations.en.links.meta.title,
        description: translations.en.links.meta.description,
        canonicalPath: "/en/links",
      };
    default:
      return undefined;
  }
};

export function LocalizedMetadata() {
  const pathname = usePathname();

  React.useEffect(() => {
    const routeMeta = getRouteMeta(pathname);

    // Route-level metadata generated by the App Router is authoritative. Only
    // update routes whose copy genuinely changes with the client locale.
    if (!routeMeta) {
      return;
    }

    const localizedTitle = routeMeta.title;
    const description = routeMeta.description;
    if (!localizedTitle || !description) {
      return;
    }
    const ogLocale = localeToOgLocale(routeMeta.locale);
    const canonicalUrl = new URL(routeMeta.canonicalPath, SITE_URL).toString();

    document.title = localizedTitle;
    upsertMeta("name", "description", description);
    upsertMeta("property", "og:title", localizedTitle);
    upsertMeta("property", "og:description", description);
    upsertMeta("property", "og:locale", ogLocale);
    upsertMeta("property", "og:url", canonicalUrl);
    upsertMeta("name", "twitter:title", localizedTitle);
    upsertMeta("name", "twitter:description", description);
    upsertLink("canonical", canonicalUrl);
  }, [pathname]);

  return null;
}
