import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { withSecurityHeaders } from "../../../../../../lib/http";
import { jsonError, loadRaceForOrganizer, requireOrganizerAuth, serviceHeaders, uuidParamSchema } from "../../../../../../lib/organizer";
import { isOrganizerRaceModuleSelected } from "../../../../../../lib/organizer-module-settings";
import { mapStartWavePayload, startWavesPayloadSchema } from "../../../../../../lib/organizer-structured-content";
import { invalidateRacebookCache } from "../../../../../../lib/racebook-cache";
const row=z.object({id:z.string().uuid(),name:z.string(),start_time:z.string(),eligibility_type:z.string(),bib_number_min:z.number().nullable(),bib_number_max:z.number().nullable(),finish_minutes_min:z.number().nullable(),finish_minutes_max:z.number().nullable(),pace_seconds_min:z.number().nullable(),pace_seconds_max:z.number().nullable(),eligibility_note:z.string().nullable(),order_index:z.number()});
const map=(r:z.infer<typeof row>)=>({id:r.id,name:r.name,startTime:r.start_time.slice(0,5),eligibilityType:r.eligibility_type,bibNumberMin:r.bib_number_min,bibNumberMax:r.bib_number_max,finishMinutesMin:r.finish_minutes_min,finishMinutesMax:r.finish_minutes_max,paceSecondsMin:r.pace_seconds_min,paceSecondsMax:r.pace_seconds_max,eligibilityNote:r.eligibility_note});
async function auth(request:NextRequest,id:string){const a=await requireOrganizerAuth(request);if("error"in a)return a;const race=await loadRaceForOrganizer(a.serviceConfig,a.user,id);if("error"in race)return race;if(!race.edition_id||!(await isOrganizerRaceModuleSelected(a.serviceConfig,race.edition_id,id,"start_waves")))return{error:jsonError("Activez la section SAS pour modifier son brouillon.",403)};return a}
async function load(config:Parameters<typeof serviceHeaders>[0],id:string){const r=await fetch(`${config.supabaseUrl}/rest/v1/race_start_waves?race_id=eq.${id}&select=id,name,start_time,eligibility_type,bib_number_min,bib_number_max,finish_minutes_min,finish_minutes_max,pace_seconds_min,pace_seconds_max,eligibility_note,order_index&order=order_index.asc`,{headers:serviceHeaders(config,""),cache:"no-store"});if(!r.ok)throw new Error();return z.array(row).parse(await r.json()).map(map)}
export async function GET(req:NextRequest,{params}:{params:{id?:string}}){const p=uuidParamSchema.safeParse(params);if(!p.success)return jsonError("Invalid race id.",400);const a=await auth(req,p.data.id);if("error"in a)return a.error;try{return withSecurityHeaders(NextResponse.json({startWaves:await load(a.serviceConfig,p.data.id)}))}catch{return jsonError("Unable to load start waves.",502)}}
export async function PUT(req:NextRequest,{params}:{params:{id?:string}}){const p=uuidParamSchema.safeParse(params);if(!p.success)return jsonError("Invalid race id.",400);const a=await auth(req,p.data.id);if("error"in a)return a.error;const b=startWavesPayloadSchema.safeParse(await req.json().catch(()=>null));if(!b.success)return jsonError(b.error.issues[0]?.message??"Invalid start waves.",400);const r=await fetch(`${a.serviceConfig.supabaseUrl}/rest/v1/rpc/replace_race_start_waves`,{method:"POST",headers:serviceHeaders(a.serviceConfig),body:JSON.stringify({p_race_id:p.data.id,p_items:b.data.startWaves.map(mapStartWavePayload)}),cache:"no-store"});if(!r.ok)return jsonError("Unable to save start waves.",502);const startWaves=z.array(row).parse(await r.json()).map(map);await invalidateRacebookCache({raceId:p.data.id});return withSecurityHeaders(NextResponse.json({startWaves}))}
