-- Add a focused Meltonic effort catalog for trail and ultra use.
-- Values are stored per consumable unit: one gel, one bar, one stick,
-- one electrolyte tablet, or one 35g drink-mix sachet for 500ml.

insert into public.products (
  slug,
  sku,
  name,
  brand,
  fuel_type,
  product_url,
  calories_kcal,
  carbs_g,
  protein_g,
  fat_g,
  sodium_mg,
  is_live,
  is_archived,
  created_by
)
values
  (
    'meltonic-boisson-energetique-bio-citron-35g',
    'MELTONIC-BOISSON-ENERGETIQUE-BIO-CITRON-35G',
    'Meltonic Boisson énergétique bio Citron 35g',
    'Meltonic',
    'drink_mix',
    'https://www.meltonic.com/fr/boisson-energetique/27-boisson-energetique-antioxydante.html',
    127,
    31.1,
    0,
    0,
    300,
    true,
    false,
    null
  ),
  (
    'meltonic-boisson-energetique-bio-fruits-rouges-35g',
    'MELTONIC-BOISSON-ENERGETIQUE-BIO-FRUITS-ROUGES-35G',
    'Meltonic Boisson énergétique bio Fruits rouges 35g',
    'Meltonic',
    'drink_mix',
    'https://www.meltonic.com/fr/boisson-energetique/267-boisson-energetique-antioxydante.html',
    128,
    32,
    0,
    0,
    300,
    true,
    false,
    null
  ),
  (
    'meltonic-boisson-energetique-bio-menthe-35g',
    'MELTONIC-BOISSON-ENERGETIQUE-BIO-MENTHE-35G',
    'Meltonic Boisson énergétique bio Menthe 35g',
    'Meltonic',
    'drink_mix',
    'https://www.meltonic.com/fr/boisson-energetique/14264-sachet-boisson-energetique-bio-menthe.html',
    128,
    32,
    0,
    0,
    300,
    true,
    false,
    null
  ),
  (
    'meltonic-electrolytes-citron-pastille',
    'MELTONIC-ELECTROLYTES-CITRON-PASTILLE',
    'Meltonic Electrolytes Citron pastille',
    'Meltonic',
    'electrolyte',
    'https://www.meltonic.com/fr/electrolytes/10636-electrolytes-citron.html',
    7,
    1.3432,
    0.0424,
    0.0146,
    311.2,
    true,
    false,
    null
  ),
  (
    'meltonic-gel-endurance-miel-ginseng-20g',
    'MELTONIC-GEL-ENDURANCE-MIEL-GINSENG-20G',
    'Meltonic Gel Endurance Miel ginseng 20g',
    'Meltonic',
    'gel',
    'https://www.meltonic.com/fr/gels-energetiques-au-miel/48-gel-energetique-endurance.html',
    57.39,
    14.2,
    0,
    0,
    0.3,
    true,
    false,
    null
  ),
  (
    'meltonic-gel-ultra-endurance-miel-curcuma-20g',
    'MELTONIC-GEL-ULTRA-ENDURANCE-MIEL-CURCUMA-20G',
    'Meltonic Gel Ultra Endurance Miel curcuma 20g',
    'Meltonic',
    'gel',
    'https://www.meltonic.com/fr/gels-energetiques-au-miel/25-gel-energetique-ultra-endurance.html',
    61.4,
    15.22,
    0.12,
    0,
    0.2,
    true,
    false,
    null
  ),
  (
    'meltonic-gel-sale-miel-fleur-de-sel-20g',
    'MELTONIC-GEL-SALE-MIEL-FLEUR-DE-SEL-20G',
    'Meltonic Gel Salé Miel fleur de sel 20g',
    'Meltonic',
    'gel',
    'https://www.meltonic.com/fr/gels-energetiques-au-miel/52-gel-energetique-sale.html',
    57.92,
    14.36,
    0.12,
    0,
    301,
    true,
    false,
    null
  ),
  (
    'meltonic-gel-antioxydant-miel-acerola-spiruline-20g',
    'MELTONIC-GEL-ANTIOXYDANT-MIEL-ACEROLA-SPIRULINE-20G',
    'Meltonic Gel Antioxydant Miel acérola spiruline 20g',
    'Meltonic',
    'gel',
    'https://www.meltonic.com/fr/gels-energetiques-au-miel/51-468-gel-energetique-antioxydant.html',
    61.4,
    15,
    0.3,
    0,
    1.62,
    true,
    false,
    null
  ),
  (
    'meltonic-gel-coup-de-frais-miel-menthe-20g',
    'MELTONIC-GEL-COUP-DE-FRAIS-MIEL-MENTHE-20G',
    'Meltonic Gel Coup de frais Miel menthe 20g',
    'Meltonic',
    'gel',
    'https://www.meltonic.com/fr/gels-energetiques-au-miel/50-gel-energetique-coup-de-frais.html',
    60.4,
    15,
    0.1,
    0,
    1.7,
    true,
    false,
    null
  ),
  (
    'meltonic-gel-coup-de-boost-miel-magnesium-guarana-20g',
    'MELTONIC-GEL-COUP-DE-BOOST-MIEL-MAGNESIUM-GUARANA-20G',
    'Meltonic Gel Coup de boost Miel magnésium guarana 20g',
    'Meltonic',
    'gel',
    'https://www.meltonic.com/fr/gels-energetiques-au-miel/49-gel-energetique-coup-de-boost.html',
    61.4,
    15.2,
    0,
    0,
    0.3,
    true,
    false,
    null
  ),
  (
    'meltonic-gel-cafeine-200mg-miel-magnesium-guarana-40g',
    'MELTONIC-GEL-CAFEINE-200MG-MIEL-MAGNESIUM-GUARANA-40G',
    'Meltonic Gel Caféine 200mg Miel magnésium guarana 40g',
    'Meltonic',
    'gel',
    'https://www.meltonic.com/fr/gels-energetiques-au-miel/10170-gel-energetique-cafe-miel-gelee-royale.html',
    117.8,
    29,
    0.4,
    0,
    0,
    true,
    false,
    null
  ),
  (
    'meltonic-puree-salee-cajou-20g',
    'MELTONIC-PUREE-SALEE-CAJOU-20G',
    'Meltonic Purée salée Cajou 20g',
    'Meltonic',
    'real_food',
    'https://www.meltonic.com/fr/purees-energetiques/8362-533-stick-puree-salee-cajou.html',
    128.6,
    4.4,
    3.8,
    10.4,
    31.5,
    true,
    false,
    null
  ),
  (
    'meltonic-puree-salee-cacahuetes-20g',
    'MELTONIC-PUREE-SALEE-CACAHUETES-20G',
    'Meltonic Purée salée Cacahuètes 20g',
    'Meltonic',
    'real_food',
    'https://www.meltonic.com/fr/purees-energetiques/8366-stick-puree-salee-cacahuetes.html',
    130.2,
    2.2,
    5,
    11,
    31.5,
    true,
    false,
    null
  ),
  (
    'meltonic-puree-salee-amande-20g',
    'MELTONIC-PUREE-SALEE-AMANDE-20G',
    'Meltonic Purée salée Amande 20g',
    'Meltonic',
    'real_food',
    'https://www.meltonic.com/fr/purees-energetiques/13688-puree-salee-amande.html',
    130,
    2.4,
    4.4,
    11,
    30.7,
    true,
    false,
    null
  ),
  (
    'meltonic-barre-pistaches-fleur-de-sel-22g',
    'MELTONIC-BARRE-PISTACHES-FLEUR-DE-SEL-22G',
    'Meltonic Barre Pistaches fleur de sel 22g',
    'Meltonic',
    'bar',
    'https://www.meltonic.com/fr/barre-energetique/35-barre-salee.html',
    82,
    13,
    1.3,
    2.3,
    225.6,
    true,
    false,
    null
  )
on conflict (slug) do update set
  sku = excluded.sku,
  name = excluded.name,
  brand = excluded.brand,
  fuel_type = excluded.fuel_type,
  product_url = excluded.product_url,
  calories_kcal = excluded.calories_kcal,
  carbs_g = excluded.carbs_g,
  protein_g = excluded.protein_g,
  fat_g = excluded.fat_g,
  sodium_mg = excluded.sodium_mg,
  is_live = excluded.is_live,
  is_archived = excluded.is_archived,
  created_by = excluded.created_by
where public.products.created_by is null;
