begin;

-- Official UTMB World Series public calendar snapshot generated by
-- scripts/scrape-utmb-world-series-catalog.mjs. GPX remains optional.
create temporary table _utmb_events (
  tenant text primary key, name text not null, location text not null,
  website_url text not null, start_date date not null, end_date date not null
) on commit drop;

insert into _utmb_events values
  ('dajingmen', 'JD Ultra-Trail Great Wall by UTMB®', 'Dajingmen, Chine', 'https://dajingmen.utmb.world', date '2026-09-11', date '2026-09-13'),
  ('wildstrubel', 'Wildstrubel by UTMB®', 'Crans Montana, Suisse', 'https://wildstrubel.utmb.world', date '2026-09-11', date '2026-09-13'),
  ('kackar', 'Kaçkar by UTMB', 'Ayder Village, Turquie', 'https://kackar.utmb.world', date '2026-09-12', date '2026-09-12'),
  ('malaysia', 'Malaysia Ultra-Trail by UTMB', 'Taiping, Perak, Malaisie', 'https://malaysia.utmb.world', date '2026-09-12', date '2026-09-12'),
  ('snowbasin', 'Snowbasin by UTMB', 'Ogden, UT, Etats-Unis', 'https://snowbasin.utmb.world', date '2026-09-12', date '2026-09-12'),
  ('grindstone', 'Grindstone Trail Running Festival', 'Natural Chimneys Park, VA, Etats-Unis', 'https://grindstone.utmb.world', date '2026-09-18', date '2026-09-19'),
  ('julianalps', 'Julian Alps Trail Run by UTMB', 'Kranjska Gora, Slovénie', 'https://julianalps.utmb.world', date '2026-09-18', date '2026-09-20'),
  ('paraty', 'Paraty Brazil by UTMB', 'Paraty, Brésil', 'https://paraty.utmb.world', date '2026-09-18', date '2026-09-20'),
  ('nice', 'Nice Côte d''Azur by UTMB®', 'Nice Côte d''Azur, France', 'https://nice.utmb.world', date '2026-09-25', date '2026-09-27'),
  ('chihuahua', 'Chihuahua by UTMB®', 'Chihuahua, Mexique', 'https://chihuahua.utmb.world', date '2026-10-02', date '2026-10-03'),
  ('transjeju', 'TransJeju by UTMB', 'Jeju World Cup Stadium, Corée du Sud', 'https://transjeju.utmb.world', date '2026-10-02', date '2026-10-03'),
  ('kodiak', 'HOKA Kodiak Ultra Marathons by UTMB', 'Big Bear Lake, California, Etats-Unis', 'https://kodiak.utmb.world', date '2026-10-09', date '2026-10-10'),
  ('mount-yun', 'Ultra-Trail Mount Yun by UTMB®', 'Mount Yun, Chine', 'https://mount-yun.utmb.world', date '2026-10-16', date '2026-10-18'),
  ('puglia', 'Puglia by UTMB', 'Castellaneta Marina, Italie', 'https://puglia.utmb.world', date '2026-10-23', date '2026-10-25'),
  ('kullamannen', 'Kullamannen by UTMB', 'Mölle, Suède', 'https://kullamannen.utmb.world', date '2026-10-30', date '2026-10-31'),
  ('mallorca', 'Mallorca by UTMB®', 'Sóller, Mallorca, Espagne', 'https://mallorca.utmb.world', date '2026-10-30', date '2026-11-01'),
  ('shudao', 'Ultra-Trail Shudao by UTMB®', 'Guangyuan, Chine', 'https://shudao.utmb.world', date '2026-11-06', date '2026-11-08'),
  ('translantau', 'Translantau™ by UTMB®', 'Lantau Island, Hong Kong, Chine', 'https://translantau.utmb.world', date '2026-11-13', date '2026-11-15'),
  ('pacifictrails', 'HOKA Pacific Trails California by UTMB', 'Rancho San Fernado Rey, Etats-Unis', 'https://pacifictrails.utmb.world', date '2026-11-14', date '2026-11-15'),
  ('bariloche', 'Patagonia BARILOCHE by UTMB', 'BARILOCHE, Patagonia Argentina, Argentine', 'https://bariloche.utmb.world', date '2026-11-20', date '2026-11-21'),
  ('kosciuszko', 'Ultra-Trail Kosciuszko by UTMB', 'Thredbo, New South Wales, Australia, Australie', 'https://kosciuszko.utmb.world', date '2026-11-26', date '2026-11-27'),
  ('chiangmai', 'HOKA Chiang Mai Thailand by UTMB®', 'PAO Park, Thaïlande', 'https://chiangmai.utmb.world', date '2026-11-28', date '2026-12-06'),
  ('oman', 'Oman by UTMB®', 'Oman', 'https://oman.utmb.world', date '2026-12-10', date '2026-12-12'),
  ('vietnamhighlands', 'Vietnam Highlands Trail by UTMB', 'Vietnam, Viêt Nam', 'https://vietnamhighlands.utmb.world', date '2027-01-09', date '2027-01-10'),
  ('arcofattrition', 'Arc of Attrition by UTMB®', 'Perranporth, Cornwall, UK, Royaume-Uni', 'https://arcofattrition.utmb.world', date '2027-01-22', date '2027-01-24'),
  ('tarawera', 'Tarawera Ultra-Trail by UTMB', 'Rotorua, New Zealand, Nouvelle-Zélande', 'https://tarawera.utmb.world', date '2027-02-13', date '2027-02-14'),
  ('puerto-vallarta', 'Puerto Vallarta by UTMB®', 'Puerto Vallarta, Mexique', 'https://puerto-vallarta.utmb.world', date '2027-03-05', date '2027-03-06'),
  ('xtrail', 'Xtrail by UTMB®', 'Kenting, Taipei Chinois', 'https://xtrail.utmb.world', date '2027-03-06', date '2027-03-07'),
  ('chianti', 'Chianti Ultra Trail by UTMB', 'Radda in Chianti, Italie', 'https://chianti.utmb.world', date '2027-03-19', date '2027-03-21'),
  ('istria', 'Istria 100 by UTMB', 'Umag, Istria, Croatie', 'https://istria.utmb.world', date '2027-04-02', date '2027-04-04'),
  ('jujuy', 'Jujuy Fuerza Sagrada by UTMB', 'Jujuy, Argentina, Argentine', 'https://jujuy.utmb.world', date '2027-04-03', date '2027-04-04'),
  ('tenerife', 'Tenerife Bluetrail by UTMB®', 'Puerto de La Cruz - Tenerife, Espagne', 'https://tenerife.utmb.world', date '2027-04-08', date '2027-04-10'),
  ('desertrats', 'Desert RATS Trail Running Festival by UTMB', 'Fruita, Colorado, Etats-Unis', 'https://desertrats.utmb.world', date '2027-04-10', date '2027-04-11'),
  ('hiroshima', 'Hiroshima Ultra-Trail by UTMB®', 'Hiroshima, Japon', 'https://hiroshima.utmb.world', date '2027-04-10', date '2027-04-11'),
  ('ventoux', 'Grand Raid Ventoux by UTMB', 'Malaucène, France', 'https://ventoux.utmb.world', date '2027-04-23', date '2027-04-25'),
  ('canyons', 'The Canyons Endurance Runs™ by UTMB®', 'Auburn, California, Etats-Unis', 'https://canyons.utmb.world', date '2027-04-23', date '2027-04-24'),
  ('ohmeudeus', 'Oh Meu Deus by UTMB', 'Seia, Portugal', 'https://ohmeudeus.utmb.world', date '2027-04-30', date '2027-05-02'),
  ('uta', 'HOKA Ultra-Trail Australia by UTMB', 'Katoomba, New South Wales,, Australie', 'https://uta.utmb.world', date '2027-05-13', date '2027-05-15'),
  ('alsace', 'Trail Alsace by UTMB', 'Obernai, France', 'https://alsace.utmb.world', date '2027-05-14', date '2027-05-16'),
  ('rothrock', 'Rothrock by UTMB', 'State College, PA, Etats-Unis', 'https://rothrock.utmb.world', date '2027-05-15', date '2027-05-16'),
  ('mut', 'Mountain Ultra Trail by UTMB', 'George, Afrique du Sud', 'https://mut.utmb.world', date '2027-05-28', date '2027-05-30'),
  ('mozart', 'mozart 100 by UTMB', 'Fuschl am see, Autriche', 'https://mozart.utmb.world', date '2027-06-05', date '2027-06-05'),
  ('chattanooga', 'Ultra Trail Chattanooga by UTMB', 'Chattanooga Tennessee, Etats-Unis', 'https://chattanooga.utmb.world', date '2027-06-05', date '2027-06-06'),
  ('andorra', 'Trail 100 Andorra by UTMB', 'Ordino, Andorre', 'https://andorra.utmb.world', date '2027-06-11', date '2027-06-13'),
  ('zugspitz', 'Zugspitz Ultra Trail by UTMB', 'Garmisch-Partenkirchen, Allemagne', 'https://zugspitz.utmb.world', date '2027-06-17', date '2027-06-19'),
  ('saint-jacques', 'Trail du Saint Jacques by UTMB', 'Le Puy en Velay, France', 'https://saint-jacques.utmb.world', date '2027-06-18', date '2027-06-20'),
  ('lavaredo', 'La Sportiva Lavaredo Ultra Trail by UTMB', 'Cortina d''Ampezzo, Italie', 'https://lavaredo.utmb.world', date '2027-06-23', date '2027-06-26'),
  ('torrencial', 'Torrencial Chile by UTMB', 'Valdivia, Chile, Chili', 'https://torrencial.utmb.world', date '2027-06-24', date '2027-06-27'),
  ('valdaran', 'HOKA Val D''Aran by UTMB®', 'Vielha - Val d''Aran, Espagne', 'https://valdaran.utmb.world', date '2027-07-07', date '2027-07-10'),
  ('verbier', 'Trail Verbier St Bernard by UTMB', 'Verbier, Suisse', 'https://verbier.utmb.world', date '2027-07-09', date '2027-07-11'),
  ('eiger', 'Eiger Ultra Trail by UTMB', 'Grindelwald, Suisse', 'https://eiger.utmb.world', date '2027-07-14', date '2027-07-17'),
  ('mrww', 'Monte Rosa Walserwaeg by UTMB', 'Gressoney Saint Jean, Italie', 'https://mrww.utmb.world', date '2027-07-16', date '2027-07-18'),
  ('kat', 'KAT100 by UTMB', 'Fieberbrunn, Autriche', 'https://kat.utmb.world', date '2027-08-05', date '2027-08-07'),
  ('gauja', 'Gauja Trail by UTMB', 'Cesis, Latvia, Lettonie', 'https://gauja.utmb.world', date '2027-08-07', date '2027-08-08'),
  ('montblanc', 'HOKA UTMB Mont-Blanc', 'Chamonix Mont-Blanc, France', 'https://montblanc.utmb.world', date '2027-08-26', date '2027-08-27');

do $$
declare source record; target_id uuid; candidate_ids uuid[];
begin
  for source in select * from _utmb_events order by tenant loop
    select array_agg(distinct event.id) into candidate_ids
    from public.race_events event
    where event.organizer_details #>> '{catalogSource,utmbTenant}' = source.tenant
       or lower(coalesce(event.website_url, '')) like '%//' || source.tenant || '.utmb.world%'
       or lower(event.name) = lower(source.name)
       or exists (
         select 1 from public.races race
         where race.event_id = event.id
           and (lower(coalesce(race.source_url, '')) like '%//' || source.tenant || '.utmb.world%'
             or lower(coalesce(race.external_site_url, '')) like '%//' || source.tenant || '.utmb.world%')
       );
    if coalesce(array_length(candidate_ids, 1), 0) > 1 then
      raise exception 'Ambiguous UTMB event binding for tenant %: %', source.tenant, candidate_ids;
    end if;
    target_id := candidate_ids[1];
    if target_id is null then
      insert into public.race_events (name, location, website_url, race_date, is_live, organizer_details)
      values (source.name, source.location, source.website_url, source.start_date, true,
        jsonb_build_object('officialWebsiteUrl', source.website_url,
          'dateRange', jsonb_build_object('endDate', source.end_date::text),
          'catalogSource', jsonb_build_object('kind', 'official', 'provider', 'utmb', 'utmbTenant', source.tenant, 'verifiedAt', '2026-09-10')))
      returning id into target_id;
    else
      update public.race_events
      set name = source.name, location = source.location, website_url = source.website_url,
          race_date = source.start_date, is_live = true,
          organizer_details = coalesce(organizer_details, '{}'::jsonb) || jsonb_build_object(
            'officialWebsiteUrl', source.website_url,
            'dateRange', jsonb_build_object('endDate', source.end_date::text),
            'catalogSource', jsonb_build_object('kind', 'official', 'provider', 'utmb', 'utmbTenant', source.tenant, 'verifiedAt', '2026-09-10')),
          updated_at = now()
      where id = target_id;
    end if;
  end loop;
end $$;

-- The partial unique index permits only one current edition per event. Clear the
-- previous marker first so an existing 2026 event can safely move to its 2027
-- official edition in the same transaction.
update public.race_event_editions edition
set is_current = false
where edition.event_id in (
  select event.id
  from _utmb_events source
  join public.race_events event
    on event.organizer_details #>> '{catalogSource,utmbTenant}' = source.tenant
)
  and edition.is_current;

insert into public.race_event_editions (event_id, edition_year, start_date, end_date, is_current, is_visible)
select event.id, extract(year from source.start_date)::smallint, source.start_date, source.end_date, true, true
from _utmb_events source
join public.race_events event on event.organizer_details #>> '{catalogSource,utmbTenant}' = source.tenant
on conflict (event_id, edition_year) do update
set start_date = least(
      excluded.start_date,
      coalesce((select min(race.race_date) from public.races race where race.edition_id = race_event_editions.id), excluded.start_date)
    ),
    end_date = greatest(
      excluded.end_date,
      coalesce((select max(race.race_date) from public.races race where race.edition_id = race_event_editions.id), excluded.end_date)
    ),
    is_current = true,
    is_visible = true;

create temporary table _utmb_races (
  event_tenant text not null, utmb_race_id bigint primary key, slug text not null,
  name text not null, race_date date not null, location text not null,
  distance_km numeric not null, elevation_gain_m numeric not null,
  source_url text not null, participation_mode text not null
) on commit drop;

insert into _utmb_races values
  ('dajingmen', 58868, 'ultra-trail-great-wall-by-utmb-cgw70-2026-utmb-58868', 'Ultra-Trail Great Wall by UTMB - CGW70', date '2026-09-11', 'Dajingmen, China', 68, 2600, 'https://dajingmen.utmb.world/races/CGW70', 'solo'),
  ('wildstrubel', 57426, 'wildstrubel-by-utmb-wild-glacier-marathon-lenk-2026-utmb-57426', 'Wildstrubel by UTMB - Wild Glacier Marathon Lenk', date '2026-09-11', 'Lenk , Switzerland', 42, 2700, 'https://wildstrubel.utmb.world/races/wild-glacier-marathon', 'solo'),
  ('dajingmen', 48218, 'ultra-trail-great-wall-by-utmb-dgw100-2026-utmb-48218', 'Ultra-Trail Great Wall by UTMB - DGW100', date '2026-09-11', 'Dajingmen, China', 100, 3800, 'https://dajingmen.utmb.world/races/DGW100', 'solo'),
  ('wildstrubel', 36638, 'wildstrubel-by-utmb-wild-70-kandersteg-2026-utmb-36638', 'Wildstrubel by UTMB - Wild 70 Kandersteg', date '2026-09-11', 'Kandersteg, Switzerland', 72, 4600, 'https://wildstrubel.utmb.world/races/wild-70', 'solo'),
  ('wildstrubel', 31123, 'wildstrubel-by-utmb-wild-110-crans-montana-2026-utmb-31123', 'Wildstrubel by UTMB - Wild 110 Crans-Montana', date '2026-09-11', 'Crans-Montana, Switzerland', 113, 6600, 'https://wildstrubel.utmb.world/races/wild-110', 'solo'),
  ('snowbasin', 59910, 'snowbasin-by-utmb-28k-2026-utmb-59910', 'Snowbasin by UTMB - 28K', date '2026-09-12', 'Snowbasin Resort, United States of America', 29, 800, 'https://snowbasin.utmb.world/races/28K', 'solo'),
  ('snowbasin', 59908, 'snowbasin-by-utmb-58k-2026-utmb-59908', 'Snowbasin by UTMB - 58K', date '2026-09-12', 'Snowbasin Resort, United States of America', 59, 1800, 'https://snowbasin.utmb.world/races/58K', 'solo'),
  ('wildstrubel', 54732, 'wildstrubel-by-utmb-wild-nextgen-crans-montana-2026-utmb-54732', 'Wildstrubel by UTMB - Wild NextGen Crans-Montana', date '2026-09-12', 'Crans-Montana, Switzerland', 10, 500, 'https://wildstrubel.utmb.world/races/Wild-NextGen', 'solo'),
  ('dajingmen', 48220, 'ultra-trail-great-wall-by-utmb-mgw50-2026-utmb-48220', 'Ultra-Trail Great Wall by UTMB - MGW50', date '2026-09-12', 'Dajingmen, China', 52, 2100, 'https://dajingmen.utmb.world/races/MGW50', 'solo'),
  ('kackar', 47834, 'kackar-by-utmb-kackar-20k-2026-utmb-47834', 'Kaçkar by UTMB - KAÇKAR 20K', date '2026-09-12', 'Ayder, Türkiye', 20, 1400, 'https://kackar.utmb.world/races/20K', 'solo'),
  ('kackar', 47832, 'kackar-by-utmb-kackar-50k-2026-utmb-47832', 'Kaçkar by UTMB - KAÇKAR 50K', date '2026-09-12', 'Ayder, Türkiye', 44, 3000, 'https://kackar.utmb.world/races/50K', 'solo'),
  ('kackar', 47830, 'kackar-by-utmb-kackar-100k-2026-utmb-47830', 'Kaçkar by UTMB - KAÇKAR 100K', date '2026-09-12', 'Ayder, Türkiye', 82, 5600, 'https://kackar.utmb.world/races/100K', 'solo'),
  ('wildstrubel', 42232, 'wildstrubel-by-utmb-wild-10-crans-montana-2026-utmb-42232', 'Wildstrubel by UTMB - Wild 10 Crans-Montana', date '2026-09-12', 'Crans-Montana, Switzerland', 10, 500, 'https://wildstrubel.utmb.world/races/wild-10', 'solo'),
  ('wildstrubel', 32450, 'wildstrubel-by-utmb-wild-55-adelboden-2026-utmb-32450', 'Wildstrubel by UTMB - Wild 55 Adelboden', date '2026-09-12', 'Adelboden, Switzerland', 55, 3300, 'https://wildstrubel.utmb.world/races/wild-55', 'solo'),
  ('malaysia', 31626, 'malaysia-ultra-trail-by-utmb-myvk-2026-utmb-31626', 'Malaysia Ultra-Trail by UTMB - MYVK', date '2026-09-12', 'Maxwell Hill / Bukit Larut, Malaysia', 5.6, 1000, 'https://malaysia.utmb.world/races/MYVK', 'solo'),
  ('malaysia', 28302, 'malaysia-ultra-trail-by-utmb-my100-2026-utmb-28302', 'Malaysia Ultra-Trail by UTMB - MY100', date '2026-09-12', 'Esplanade Taiping, Perak, Malaysia', 97.7, 4802, 'https://malaysia.utmb.world/races/MY100', 'solo'),
  ('malaysia', 19031, 'malaysia-ultra-trail-by-utmb-my50-2026-utmb-19031', 'Malaysia Ultra-Trail by UTMB - MY50', date '2026-09-12', 'Jalan Kota, Taiping, Malaysia', 54.53, 1977, 'https://malaysia.utmb.world/races/MY50', 'solo'),
  ('malaysia', 19029, 'malaysia-ultra-trail-by-utmb-my25-2026-utmb-19029', 'Malaysia Ultra-Trail by UTMB - MY25', date '2026-09-12', 'Jalan Kota, Taiping, Perak, Malaysia', 25.92, 1012, 'https://malaysia.utmb.world/races/MY25', 'solo'),
  ('malaysia', 19027, 'malaysia-ultra-trail-by-utmb-my13-2026-utmb-19027', 'Malaysia Ultra-Trail by UTMB - MY13', date '2026-09-12', 'Jalan Kota Taiping, Perak, Malaysia', 13.9, 382, 'https://malaysia.utmb.world/races/MY13', 'solo'),
  ('dajingmen', 48222, 'ultra-trail-great-wall-by-utmb-ngw30-2026-utmb-48222', 'Ultra-Trail Great Wall by UTMB - NGW30', date '2026-09-13', 'Dajingmen, China', 31, 1460, 'https://dajingmen.utmb.world/races/NGW30', 'solo'),
  ('wildstrubel', 32452, 'wildstrubel-by-utmb-wild-25-leukerbad-2026-utmb-32452', 'Wildstrubel by UTMB - Wild 25 Leukerbad', date '2026-09-13', 'Leukerbad, Switzerland', 26, 1200, 'https://wildstrubel.utmb.world/races/wild-25', 'solo'),
  ('paraty', 35706, 'paraty-brazil-by-utmb-ptr-108-2026-utmb-35706', 'Paraty Brazil by UTMB - PTR 108', date '2026-09-18', 'Paraty - Centro Histórico, Brazil', 101, 4850, 'https://paraty.utmb.world/races/ptr108', 'solo'),
  ('julianalps', 24705, 'julian-alps-trail-run-by-utmb-sky-trail-50k-2026-utmb-24705', 'Julian Alps Trail Run by UTMB - SKY TRAIL 50K', date '2026-09-18', 'Žirovnica, Slovenia', 55, 2828, 'https://julianalps.utmb.world/races/50K', 'solo'),
  ('julianalps', 18649, 'julian-alps-trail-run-by-utmb-i-feel-slovenia-120k-2026-utmb-18649', 'Julian Alps Trail Run by UTMB - I FEEL SLOVENIA 120K', date '2026-09-18', 'Radovljica, Slovenia', 122, 5855, 'https://julianalps.utmb.world/races/120K', 'solo'),
  ('grindstone', 681, 'grindstone-trail-running-festival-by-utmb-100m-2026-utmb-681', 'Grindstone Trail Running Festival by UTMB - 100M', date '2026-09-18', 'Natural Chimneys Park, United States of America', 167.4, 6400, 'https://grindstone.utmb.world/races/100M', 'solo'),
  ('paraty', 60104, 'paraty-brazil-by-utmb-ptr-17-2026-utmb-60104', 'Paraty Brazil by UTMB - PTR 17', date '2026-09-19', 'Fazenda Bananal, Brazil', 17, 600, 'https://paraty.utmb.world/races/ptr17', 'solo'),
  ('grindstone', 42692, 'grindstone-trail-running-festival-by-utmb-50k-2026-utmb-42692', 'Grindstone Trail Running Festival by UTMB - 50K', date '2026-09-19', 'Natural Chimneys Park, United States of America', 50, 1550, 'https://grindstone.utmb.world/races/50K', 'solo'),
  ('grindstone', 37040, 'grindstone-trail-running-festival-by-utmb-21k-2026-utmb-37040', 'Grindstone Trail Running Festival by UTMB - 21K', date '2026-09-19', 'Natural Chimneys Park, United States of America', 21, 500, 'https://grindstone.utmb.world/races/21K', 'solo'),
  ('grindstone', 37038, 'grindstone-trail-running-festival-by-utmb-100k-2026-utmb-37038', 'Grindstone Trail Running Festival by UTMB - 100K', date '2026-09-19', 'Natural Chimneys Park, VA, United States of America', 100, 3350, 'https://grindstone.utmb.world/races/100K', 'solo'),
  ('paraty', 35712, 'paraty-brazil-by-utmb-ptr-25-2026-utmb-35712', 'Paraty Brazil by UTMB - PTR 25', date '2026-09-19', 'Paraty - Centro Histórico, Brazil', 25, 750, 'https://paraty.utmb.world/races/ptr25', 'solo'),
  ('paraty', 35710, 'paraty-brazil-by-utmb-ptr-34-2026-utmb-35710', 'Paraty Brazil by UTMB - PTR 34', date '2026-09-19', 'Paraty - Centro Histórico, Brazil', 34, 1150, 'https://paraty.utmb.world/races/ptr34', 'solo'),
  ('paraty', 35708, 'paraty-brazil-by-utmb-ptr-58-2026-utmb-35708', 'Paraty Brazil by UTMB - PTR 58', date '2026-09-19', 'Paraty - Centro Histórico, Brazil', 58, 3400, 'https://paraty.utmb.world/races/ptr58', 'solo'),
  ('julianalps', 18647, 'julian-alps-trail-run-by-utmb-lake-bled-80k-2026-utmb-18647', 'Julian Alps Trail Run by UTMB - LAKE BLED 80K', date '2026-09-19', 'Bled, Slovenia', 80, 3866, 'https://julianalps.utmb.world/races/80K', 'solo'),
  ('paraty', 50428, 'paraty-brazil-by-utmb-fun-7k-2026-utmb-50428', 'Paraty Brazil by UTMB - FUN 7K', date '2026-09-20', 'Paraty , Brazil', 7, 50, 'https://paraty.utmb.world/races', 'solo'),
  ('julianalps', 24711, 'julian-alps-trail-run-by-utmb-funny-10k-2026-utmb-24711', 'Julian Alps Trail Run by UTMB - FUNNY 10K', date '2026-09-20', 'Kranjska Gora, Slovenia', 11, 329, 'https://julianalps.utmb.world/races/10K', 'solo'),
  ('julianalps', 24709, 'julian-alps-trail-run-by-utmb-intersport-speed-15k-2026-utmb-24709', 'Julian Alps Trail Run by UTMB - INTERSPORT SPEED 15K', date '2026-09-20', 'Kranjska Gora, Slovenia', 17, 583, 'https://julianalps.utmb.world/races/15K', 'solo'),
  ('julianalps', 24707, 'julian-alps-trail-run-by-utmb-kranjska-gora-25k-2026-utmb-24707', 'Julian Alps Trail Run by UTMB - KRANJSKA GORA 25K', date '2026-09-20', 'Kranjska Gora, Slovenia', 25, 1090, 'https://julianalps.utmb.world/races/25K', 'solo'),
  ('nice', 63274, 'nice-cote-d-azur-by-utmb-levens-nice-50k-2026-utmb-63274', 'Nice Côte d’Azur by UTMB® - Levens - Nice - 50K', date '2026-09-25', 'Levens, France', 39, 1388, 'https://nice.utmb.world/races/TEST-Nice-50k', 'solo'),
  ('nice', 31181, 'nice-cote-d-azur-by-utmb-ultra-trail-metropole-nice-cote-d-azur-100m-2026-utmb-31181', 'Nice Côte d’Azur by UTMB® - Ultra Trail Métropole Nice Côte d’Azur - 100M', date '2026-09-25', 'Auron, France', 165, 8900, 'https://nice.utmb.world/races/nice-100m', 'solo'),
  ('nice', 32446, 'nice-cote-d-azur-by-utmb-eze-nice-50k-2026-utmb-32446', 'Nice Côte d’Azur by UTMB® - Eze - Nice - 50K', date '2026-09-26', 'Eze, France', 50, 2000, 'https://nice.utmb.world/races/Nice-50k', 'solo'),
  ('nice', 32444, 'nice-cote-d-azur-by-utmb-roubion-nice-100k-2026-utmb-32444', 'Nice Côte d’Azur by UTMB® - Roubion - Nice - 100K', date '2026-09-26', 'Roubion, France', 109, 5400, 'https://nice.utmb.world/races/nice-100k', 'solo'),
  ('nice', 32448, 'nice-cote-d-azur-by-utmb-saint-jean-cap-ferrat-nice-20k-2026-utmb-32448', 'Nice Côte d’Azur by UTMB® - Saint-Jean-Cap-Ferrat - Nice - 20K', date '2026-09-27', 'Saint-Jean Cap Ferrat, France', 23, 680, 'https://nice.utmb.world/races/nice-20k', 'solo'),
  ('transjeju', 52070, 'transjeju-by-utmb-jeju100m-2026-utmb-52070', 'TransJeju by UTMB - Jeju100M', date '2026-10-02', 'Jeju World-cup Stadium, South Korea', 148, 5000, 'https://transjeju.utmb.world/races/Jeju100M', 'solo'),
  ('chihuahua', 47716, 'chihuahua-by-utmb-akaa-58k-2026-utmb-47716', 'Chihuahua by UTMB - Akáa 58K', date '2026-10-02', 'Parque Barrancas, Divisadero, Mexico', 58, 2500, 'https://chihuahua.utmb.world/races/50K', 'solo'),
  ('chihuahua', 47714, 'chihuahua-by-utmb-weriga-93k-2026-utmb-47714', 'Chihuahua by UTMB - Weriga 93K', date '2026-10-02', 'Cerocahui, Mexico', 93, 4700, 'https://chihuahua.utmb.world/races/100K', 'solo'),
  ('chihuahua', 47712, 'chihuahua-by-utmb-raramuri-100m-2026-utmb-47712', 'Chihuahua by UTMB - Rarámuri 100M', date '2026-10-02', 'Cerocahui, Mexico', 118, 5600, 'https://chihuahua.utmb.world/races/100M', 'solo'),
  ('chihuahua', 47722, 'chihuahua-by-utmb-norawa-9k-2026-utmb-47722', 'Chihuahua by UTMB - Norawa 9K', date '2026-10-03', 'Parque Barrancas, Divisadero', 9, 200, 'https://chihuahua.utmb.world/races/9K', 'solo'),
  ('chihuahua', 47720, 'chihuahua-by-utmb-napurega-21k-2026-utmb-47720', 'Chihuahua by UTMB - Napurega 21K', date '2026-10-03', 'Parque Barrancas, Divisadero, Mexico', 21, 700, 'https://chihuahua.utmb.world/races/20K', 'solo'),
  ('chihuahua', 47718, 'chihuahua-by-utmb-komakali-39k-2026-utmb-47718', 'Chihuahua by UTMB - Komakali 39K', date '2026-10-03', 'Parque Barrancas, Divisadero, Mexico', 39, 1700, 'https://chihuahua.utmb.world/races/38K', 'solo'),
  ('transjeju', 36778, 'transjeju-by-utmb-jeju20k-2026-utmb-36778', 'TransJeju by UTMB - Jeju20K', date '2026-10-03', 'Gasiri Horse Park, South Korea', 20, 508, 'https://transjeju.utmb.world/races/Jeju20K', 'solo'),
  ('transjeju', 8699, 'transjeju-by-utmb-jeju60k-2026-utmb-8699', 'TransJeju by UTMB - Jeju60K', date '2026-10-03', 'Gasiri, South Korea', 60, 1400, 'https://transjeju.utmb.world/races/Jeju70K', 'solo'),
  ('transjeju', 8697, 'transjeju-by-utmb-jeju100k-2026-utmb-8697', 'TransJeju by UTMB - Jeju100K', date '2026-10-03', 'Jeju World Cup Stadium, South Korea', 104, 4000, 'https://transjeju.utmb.world/races/Jeju100K', 'solo'),
  ('kodiak', 2452, 'kodiak-ultra-marathons-by-utmb-100m-2026-utmb-2452', 'Kodiak Ultra Marathons by UTMB - 100M', date '2026-10-09', 'Rim Nordic Ski Area, United States of America', 100.3, 16000, 'https://kodiak.utmb.world/races/100M', 'solo'),
  ('kodiak', 39254, 'kodiak-ultra-marathons-by-utmb-10k-2026-utmb-39254', 'Kodiak Ultra Marathons by UTMB - 10K', date '2026-10-10', 'The Village of Big Bear Lake, United States of America', 10.5, 280, 'https://kodiak.utmb.world/races/10K', 'solo'),
  ('kodiak', 33800, 'kodiak-ultra-marathons-by-utmb-50k-2026-utmb-33800', 'Kodiak Ultra Marathons by UTMB - 50K', date '2026-10-10', 'The Village of Big Bear Lake, United States of America', 48.4, 1339, 'https://kodiak.utmb.world/races/50K', 'solo'),
  ('kodiak', 29668, 'kodiak-ultra-marathons-by-utmb-21k-2026-utmb-29668', 'Kodiak Ultra Marathons by UTMB - 21K', date '2026-10-10', 'The Village of Big Bear Lake, United States of America', 13.4, 2110, 'https://kodiak.utmb.world/races/21K', 'solo'),
  ('kodiak', 29667, 'kodiak-ultra-marathons-by-utmb-100k-2026-utmb-29667', 'Kodiak Ultra Marathons by UTMB - 100K', date '2026-10-10', 'The Village of Big Bear Lake, United States of America', 99, 3120, 'https://kodiak.utmb.world/races/100K', 'solo'),
  ('mount-yun', 47610, 'mount-yun-by-utmb-umy-100m-2026-utmb-47610', 'Mount Yun by UTMB - UMY 100M', date '2026-10-16', 'Zhonghe Square, China', 161, 6500, 'https://mount-yun.utmb.world/races/100M', 'solo'),
  ('mount-yun', 41384, 'mount-yun-by-utmb-dmy-100k-2026-utmb-41384', 'Mount Yun by UTMB - DMY 100K', date '2026-10-16', 'Zhonghe Square, China', 97, 4300, 'https://mount-yun.utmb.world/races/100K', 'solo'),
  ('mount-yun', 47618, 'mount-yun-by-utmb-cmy-70k-2026-utmb-47618', 'Mount Yun by UTMB - CMY 70K', date '2026-10-17', 'Zhonghe Square, China', 68, 2600, 'https://mount-yun.utmb.world/races/70K', 'solo'),
  ('mount-yun', 41386, 'mount-yun-by-utmb-mmy-50k-2026-utmb-41386', 'Mount Yun by UTMB - MMY 50K', date '2026-10-17', 'Zhonghe Square in Mount Yun, China', 48, 2400, 'https://mount-yun.utmb.world/races/50K', 'solo'),
  ('mount-yun', 41388, 'mount-yun-by-utmb-emy-20k-2026-utmb-41388', 'Mount Yun by UTMB - EMY 20K', date '2026-10-18', 'Zhonghe Square in Mount Yun, China', 22, 1300, 'https://mount-yun.utmb.world/races/20K', 'solo'),
  ('puglia', 52848, 'puglia-by-utmb-i-sassi-di-matera-2026-utmb-52848', 'PUGLIA BY UTMB® - I Sassi di Matera', date '2026-10-23', 'Matera, Italy', 145, 3500, 'https://puglia.utmb.world/races/SDM', 'solo'),
  ('puglia', 52856, 'puglia-by-utmb-costa-verde-trail-2026-utmb-52856', 'PUGLIA BY UTMB® - Costa Verde Trail', date '2026-10-24', 'Castellaneta Marina, Italy', 10, 50, 'https://puglia.utmb.world/races/CVT10', 'solo'),
  ('puglia', 52850, 'puglia-by-utmb-le-maioliche-di-laterza-2026-utmb-52850', 'PUGLIA BY UTMB® - Le Maioliche di Laterza', date '2026-10-24', 'Laterza, Italy', 85, 2000, 'https://puglia.utmb.world/races/MLT85', 'solo'),
  ('puglia', 52854, 'puglia-by-utmb-ginosa-rivolta-trail-2026-utmb-52854', 'PUGLIA BY UTMB® - Ginosa Rivolta Trail', date '2026-10-25', 'Ginosa, Italy', 35, 350, 'https://puglia.utmb.world/races/GRT35', 'solo'),
  ('puglia', 52852, 'puglia-by-utmb-castellaneta-underground-trail-2026-utmb-52852', 'PUGLIA BY UTMB® - Castellaneta Underground Trail', date '2026-10-25', 'Castellaneta, Italy', 50, 1000, 'https://puglia.utmb.world/races/CUT50', 'solo'),
  ('mallorca', 44436, 'mallorca-by-utmb-serra-de-tramuntana-sdt-2026-utmb-44436', 'Mallorca by UTMB - Serra de Tramuntana (SDT)', date '2026-10-30', 'CALA ESTELLENCS, Spain', 138, 5350, 'https://mallorca.utmb.world/races/100M', 'solo'),
  ('kullamannen', 22553, 'kullamannen-by-utmb-sprint-ultra-100-km-2026-utmb-22553', 'Kullamannen by UTMB - Sprint Ultra 100 km', date '2026-10-30', 'Höganäs Church, Sweden', 108, 749, 'https://kullamannen.utmb.world/races/sprint-ultra-100-km', 'solo'),
  ('kullamannen', 10675, 'kullamannen-by-utmb-ultra-100-miles-2026-utmb-10675', 'Kullamannen by UTMB - Ultra 100 Miles', date '2026-10-30', 'Höganäs Church, Sweden', 173, 2300, 'https://kullamannen.utmb.world/races/ultra-100-miles', 'solo'),
  ('mallorca', 44440, 'mallorca-by-utmb-els-tres-mils-etm-2026-utmb-44440', 'Mallorca by UTMB - Els Tres Mils (ETM)', date '2026-10-31', 'SELVA, Spain', 56, 2450, 'https://mallorca.utmb.world/races/50K', 'solo'),
  ('mallorca', 44438, 'mallorca-by-utmb-camins-de-pedra-en-sec-cps-2026-utmb-44438', 'Mallorca by UTMB - Camins de pedra en sec (CPS)', date '2026-10-31', 'CALA ESTELLENCS, Spain', 104, 3740, 'https://mallorca.utmb.world/races/100K', 'solo'),
  ('kullamannen', 32646, 'kullamannen-by-utmb-north-shore-2026-utmb-32646', 'Kullamannen by UTMB - North Shore', date '2026-10-31', 'Hotel Skansen Seaside, Sweden', 22, 96, 'https://kullamannen.utmb.world/races/north-shore', 'solo'),
  ('kullamannen', 30675, 'kullamannen-by-utmb-seventh-seal-2026-utmb-30675', 'Kullamannen by UTMB - Seventh Seal', date '2026-10-31', 'Båstad Skansen Beach, Sweden', 53, 727, 'https://kullamannen.utmb.world/races/seventh-seal', 'solo'),
  ('mallorca', 44442, 'mallorca-by-utmb-camins-de-s-arxiduc-cda-2026-utmb-44442', 'Mallorca by UTMB - Camins de s''Arxiduc (CDA)', date '2026-11-01', 'VALLDEMOSSA, Spain', 26, 1000, 'https://mallorca.utmb.world/races/20K', 'solo'),
  ('shudao', 54814, 'ultra-trail-shudao-by-utmb-dsd-100k-2026-utmb-54814', 'Ultra-Trail Shudao by UTMB - DSD 100K', date '2026-11-06', 'Jiange Tourist Center, China', 104, 3800, 'https://shudao.utmb.world/races/100K', 'solo'),
  ('shudao', 60508, 'ultra-trail-shudao-by-utmb-csd-70k-2026-utmb-60508', 'Ultra-Trail Shudao by UTMB - CSD 70K', date '2026-11-07', 'Zhaohua Ancient Town, China', 70.5, 3100, 'https://shudao.utmb.world/races/70K', 'solo'),
  ('shudao', 54816, 'ultra-trail-shudao-by-utmb-msd-50k-2026-utmb-54816', 'Ultra-Trail Shudao by UTMB - MSD 50K', date '2026-11-07', 'Zhaohua Ancient Town, China', 42, 1900, 'https://shudao.utmb.world/races/50K', 'solo'),
  ('shudao', 54818, 'ultra-trail-shudao-by-utmb-esd-20k-2026-utmb-54818', 'Ultra-Trail Shudao by UTMB - ESD 20K', date '2026-11-08', 'Zhaohua Ancient Town, China', 21.5, 900, 'https://shudao.utmb.world/races/20K', 'solo'),
  ('translantau', 1673, 'translantau-by-utmb-translantau100-2026-utmb-1673', 'TransLantau by UTMB - TransLantau100', date '2026-11-13', 'Mui Wo River Silver Garden, Hong Kong, China', 104, 4500, 'https://translantau.utmb.world/races/tl100', 'solo'),
  ('pacifictrails', 54684, 'hoka-pacific-trails-california-by-utmb-50k-2026-utmb-54684', 'HOKA Pacific Trails California by UTMB - 50K', date '2026-11-14', 'Rancho San Fernando Rey, United States of America', 51, 1550, 'https://pacifictrails.utmb.world/races/50K', 'solo'),
  ('translantau', 1326, 'translantau-by-utmb-translantau50-2026-utmb-1326', 'TransLantau by UTMB - TransLantau50', date '2026-11-14', 'Mui Wo River Silver Garden, Hong Kong, China', 45, 2500, 'https://translantau.utmb.world/races/tl50', 'solo'),
  ('translantau', 61466, 'translantau-by-utmb-translantau15-2026-utmb-61466', 'TransLantau by UTMB - TransLantau15', date '2026-11-15', 'Mui Wo, Hong Kong, China', 15, 500, 'https://translantau.utmb.world/races/tl15', 'solo'),
  ('pacifictrails', 54690, 'hoka-pacific-trails-california-by-utmb-25k-2026-utmb-54690', 'HOKA Pacific Trails California by UTMB - 25K', date '2026-11-15', 'Rancho San Fernando Rey, United States of America', 25, 650, 'https://pacifictrails.utmb.world/races/25K', 'solo'),
  ('translantau', 6789, 'translantau-by-utmb-translantau25-2026-utmb-6789', 'TransLantau by UTMB - TransLantau25', date '2026-11-15', 'Mui Wo River Silver Garden, Hong Kong, China', 27, 1100, 'https://translantau.utmb.world/races/tl25', 'solo'),
  ('bariloche', 52676, 'bariloche-patagonia-by-utmb-nahuel-huapi-33k-2026-utmb-52676', 'Bariloche Patagonia by UTMB - NAHUEL HUAPI 33K', date '2026-11-20', 'Los Baqueanos, Argentina', 36, 1421, 'https://bariloche.utmb.world/races/NAHUELHUAPI', 'solo'),
  ('bariloche', 52674, 'bariloche-patagonia-by-utmb-bella-vista-55k-2026-utmb-52674', 'Bariloche Patagonia by UTMB - BELLA VISTA 55K', date '2026-11-20', 'Los Baqueanos, Argentina', 57.5, 3000, 'https://bariloche.utmb.world/races/BELLAVISTA', 'solo'),
  ('bariloche', 52670, 'bariloche-patagonia-by-utmb-tronador-130k-2026-utmb-52670', 'Bariloche Patagonia by UTMB - TRONADOR 130K', date '2026-11-20', 'Bariloche, Argentina', 132, 6516, 'https://bariloche.utmb.world/races/TRONADOR', 'solo'),
  ('bariloche', 52680, 'bariloche-patagonia-by-utmb-otto-12k-2026-utmb-52680', 'Bariloche Patagonia by UTMB - OTTO 12K', date '2026-11-21', 'Otto, Argentina', 12.7, 500, 'https://bariloche.utmb.world/races/OTTO', 'solo'),
  ('bariloche', 52678, 'bariloche-patagonia-by-utmb-cerro-lindo-22k-2026-utmb-52678', 'Bariloche Patagonia by UTMB - CERRO LINDO 22K', date '2026-11-21', 'Cerro Lindo, Argentina', 22, 800, 'https://bariloche.utmb.world/races/CERROLINDO', 'solo'),
  ('bariloche', 52672, 'bariloche-patagonia-by-utmb-frey-85k-2026-utmb-52672', 'Bariloche Patagonia by UTMB - FREY 85K', date '2026-11-21', 'BARILOCHE, Argentina', 86, 4725, 'https://bariloche.utmb.world/races/FREY', 'solo'),
  ('kosciuszko', 33954, 'ultra-trail-kosciuszko-by-utmb-kosci30-2026-utmb-33954', 'Ultra-Trail Kosciuszko by UTMB - Kosci30', date '2026-11-26', 'Perisher Ski Resort, Australia', 32, 670, 'https://kosciuszko.utmb.world/races/kosci-30', 'solo'),
  ('kosciuszko', 33952, 'ultra-trail-kosciuszko-by-utmb-kosci50-2026-utmb-33952', 'Ultra-Trail Kosciuszko by UTMB - Kosci50', date '2026-11-26', 'Perisher Ski Resort, Australia', 50, 1400, 'https://kosciuszko.utmb.world/races/kosci-50', 'solo'),
  ('kosciuszko', 33950, 'ultra-trail-kosciuszko-by-utmb-kosci100-2026-utmb-33950', 'Ultra-Trail Kosciuszko by UTMB - Kosci100', date '2026-11-27', 'Perisher Ski Resort, Australia', 106, 3260, 'https://kosciuszko.utmb.world/races/kosci-100', 'solo'),
  ('kosciuszko', 33948, 'ultra-trail-kosciuszko-by-utmb-koscimiler-2026-utmb-33948', 'Ultra-Trail Kosciuszko by UTMB - KosciMiler', date '2026-11-27', 'Banjo Patterson Park, Jindabyne, Australia', 161, 5131, 'https://kosciuszko.utmb.world/races/kosci-miler', 'solo'),
  ('chiangmai', 63230, 'chiangmai-thailand-by-utmb-pagoda-50-night-2026-utmb-63230', 'Chiangmai Thailand by UTMB® - PAGODA 50-NIGHT', date '2026-11-28', 'Doi Inthanon National Park HQ, Thailand', 57, 3600, 'https://chiangmai.utmb.world/races/PAGODA50-NIGHT', 'solo'),
  ('chiangmai', 63228, 'chiangmai-thailand-by-utmb-pagoda-50-day-2026-utmb-63228', 'Chiangmai Thailand by UTMB® - PAGODA 50-DAY', date '2026-11-28', 'Doi Inthanon National Park HQ, Thailand', 57, 3600, 'https://chiangmai.utmb.world/races/PAGODA50-DAY', 'solo'),
  ('chiangmai', 53806, 'chiangmai-thailand-by-utmb-inthanon-20-2026-utmb-53806', 'Chiangmai Thailand by UTMB® - INTHANON 20', date '2026-11-29', 'Doi Inthanon National Park Headquarters, Thailand', 20, 800, 'https://chiangmai.utmb.world/races/INTHANON20', 'solo'),
  ('chiangmai', 25273, 'chiangmai-thailand-by-utmb-chiang-dao-160-2026-utmb-25273', 'Chiangmai Thailand by UTMB® - CHIANG DAO 160', date '2026-12-04', 'Wat Tham Chiang Dao, Thailand', 173, 9800, 'https://chiangmai.utmb.world/races/CHIANGDAO160', 'solo'),
  ('chiangmai', 25271, 'chiangmai-thailand-by-utmb-elephant-100-2026-utmb-25271', 'Chiangmai Thailand by UTMB® - ELEPHANT 100', date '2026-12-04', 'Wat Nhong Bua Noi, Thailand', 100, 5500, 'https://chiangmai.utmb.world/races/ELEPHANT100', 'solo'),
  ('chiangmai', 53802, 'chiangmai-thailand-by-utmb-suthep-20-night-2026-utmb-53802', 'Chiangmai Thailand by UTMB® - SUTHEP 20-NIGHT', date '2026-12-05', 'Chiang Mai PAO Park, Thailand', 26, 1100, 'https://chiangmai.utmb.world/races/SUTHEP20-NIGHT', 'solo'),
  ('chiangmai', 53800, 'chiangmai-thailand-by-utmb-hmong-50-night-2026-utmb-53800', 'Chiangmai Thailand by UTMB® - HMONG 50-NIGHT', date '2026-12-05', 'Chiang Mai PAO Park, Thailand', 63, 3000, 'https://chiangmai.utmb.world/races/HMONG50-NIGHT', 'solo'),
  ('chiangmai', 25269, 'chiangmai-thailand-by-utmb-hmong-50-day-2026-utmb-25269', 'Chiangmai Thailand by UTMB® - HMONG 50-DAY', date '2026-12-05', 'Chiang Mai PAO Park, Thailand', 63, 3000, 'https://chiangmai.utmb.world/races/HMONG50-DAY', 'solo'),
  ('chiangmai', 27502, 'chiangmai-thailand-by-utmb-chedi-20-2026-utmb-27502', 'Chiangmai Thailand by UTMB® - CHEDI 20', date '2026-12-06', 'Chiang Mai PAO Park, Thailand', 17, 700, 'https://chiangmai.utmb.world/races/CHEDI20', 'solo'),
  ('chiangmai', 25267, 'chiangmai-thailand-by-utmb-suthep-20-day-2026-utmb-25267', 'Chiangmai Thailand by UTMB® - SUTHEP 20-DAY', date '2026-12-06', 'Chiang Mai PAO Park, Thailand', 26, 1100, 'https://chiangmai.utmb.world/races/SUTHEP20-DAY', 'solo'),
  ('oman', 59398, 'oman-by-utmb-jabal-classic-2026-utmb-59398', 'Oman by UTMB - JABAL CLASSIC', date '2026-12-10', 'Al Hamra, Oman', 103, 5000, 'https://oman.utmb.world/races/JAC', 'solo'),
  ('oman', 37544, 'oman-by-utmb-hajar-ultra-2026-utmb-37544', 'Oman by UTMB - HAJAR ULTRA', date '2026-12-10', 'Al Hamra, Oman', 154, 8000, 'https://oman.utmb.world/races/HAJ', 'solo'),
  ('oman', 42146, 'oman-by-utmb-skyward-canyon-2026-utmb-42146', 'Oman by UTMB - SKYWARD CANYON', date '2026-12-11', 'Izki, Oman', 50, 2400, 'https://oman.utmb.world/races/SKY', 'solo'),
  ('oman', 56214, 'oman-by-utmb-old-capital-trail-2026-utmb-56214', 'Oman by UTMB - OLD CAPITAL TRAIL', date '2026-12-12', 'Nizwa, Oman', 32, 1400, 'https://oman.utmb.world/races/OCT', 'solo'),
  ('oman', 42148, 'oman-by-utmb-scenic-ascent-2026-utmb-42148', 'Oman by UTMB - SCENIC ASCENT', date '2026-12-12', 'Birkat Almouz, Oman', 21.5, 550, 'https://oman.utmb.world/races/SAS', 'solo'),
  ('vietnamhighlands', 62692, 'vietnam-highlands-trail-by-utmb-100k-langbiang-2027-utmb-62692', 'Vietnam Highlands Trail by UTMB - 100K LANGBIANG', date '2027-01-09', 'Lam Vien Square, Vietnam', 104.2, 5533, 'https://vietnamhighlands.utmb.world/races/100Klangbiang', 'solo'),
  ('vietnamhighlands', 56354, 'vietnam-highlands-trail-by-utmb-10k-tuyenlam-2027-utmb-56354', 'Vietnam Highlands Trail by UTMB - 10K TUYENLAM', date '2027-01-09', 'Clay Tunnel, Vietnam', 11.3, 486, 'https://vietnamhighlands.utmb.world/races/10Ktuyenlam', 'solo'),
  ('vietnamhighlands', 56352, 'vietnam-highlands-trail-by-utmb-20k-pinhatt-2027-utmb-56352', 'Vietnam Highlands Trail by UTMB - 20K PINHATT', date '2027-01-09', 'Clay Tunnel, Vietnam', 24.1, 1113, 'https://vietnamhighlands.utmb.world/races/20Kpinhatt', 'solo'),
  ('vietnamhighlands', 56350, 'vietnam-highlands-trail-by-utmb-50k-elephant-2027-utmb-56350', 'Vietnam Highlands Trail by UTMB - 50K ELEPHANT', date '2027-01-09', 'Lam Vien Square, Vietnam', 56.4, 2946, 'https://vietnamhighlands.utmb.world/races/50Kelephant', 'solo'),
  ('vietnamhighlands', 62696, 'vietnam-highlands-trail-by-utmb-5k-xuanhuong-2027-utmb-62696', 'Vietnam Highlands Trail by UTMB - 5K XUANHUONG', date '2027-01-10', 'Lam Vien Square, Vietnam', 5, 50, 'https://vietnamhighlands.utmb.world/races', 'solo'),
  ('arcofattrition', 2705, 'arc-of-attrition-by-utmb-arc-100-2027-utmb-2705', 'Arc Of Attrition by UTMB - Arc 100', date '2027-01-22', 'Coverack, United Kingdom', 161.2, 5300, 'https://arcofattrition.utmb.world/races', 'solo'),
  ('arcofattrition', 12555, 'arc-of-attrition-by-utmb-arc-50-2027-utmb-12555', 'Arc Of Attrition by UTMB - Arc 50', date '2027-01-23', 'Porthcurno, United Kingdom', 80.5, 2550, 'https://arcofattrition.utmb.world/races', 'solo'),
  ('arcofattrition', 52246, 'arc-of-attrition-by-utmb-arc-12-2027-utmb-52246', 'Arc Of Attrition by UTMB - Arc 12', date '2027-01-24', 'Godrevy, United Kingdom', 24.2, 980, 'https://arcofattrition.utmb.world/races', 'solo'),
  ('arcofattrition', 45528, 'arc-of-attrition-by-utmb-arc-25-2027-utmb-45528', 'Arc Of Attrition by UTMB - Arc 25', date '2027-01-24', 'St Ives, United Kingdom', 41.2, 1240, 'https://arcofattrition.utmb.world/races', 'solo'),
  ('tarawera', 34752, 'tarawera-ultra-trail-by-utmb-t21-2027-utmb-34752', 'Tarawera Ultra-Trail by UTMB® - T21', date '2027-02-13', 'Lake Tikitapu (Blue Lake) Reserve, New Zealand', 23, 400, 'https://tarawera.utmb.world/races/t-21', 'solo'),
  ('tarawera', 11949, 'tarawera-ultra-trail-by-utmb-tmiler-2027-utmb-11949', 'Tarawera Ultra-Trail by UTMB® - TMiler', date '2027-02-13', 'Te Puia, Rotorua, New Zealand', 163, 3800, 'https://tarawera.utmb.world/races/t-miler', 'solo'),
  ('tarawera', 3638, 'tarawera-ultra-trail-by-utmb-t50-2027-utmb-3638', 'Tarawera Ultra-Trail by UTMB® - T50', date '2027-02-13', 'Te Puia, Rotorua, New Zealand', 52, 1150, 'https://tarawera.utmb.world/races/t-50', 'solo'),
  ('tarawera', 895, 'tarawera-ultra-trail-by-utmb-t102-2027-utmb-895', 'Tarawera Ultra-Trail by UTMB® - T102', date '2027-02-13', 'Firmin Field, Kawerau, New Zealand', 102, 2300, 'https://tarawera.utmb.world/races/t-102', 'solo'),
  ('tarawera', 61656, 'tarawera-ultra-trail-by-utmb-t14-2027-utmb-61656', 'Tarawera Ultra-Trail by UTMB® - T14', date '2027-02-14', 'Te Puia, Rotorua, New Zealand', 14, 161, 'https://tarawera.utmb.world/races/t-14', 'solo'),
  ('puerto-vallarta', 32458, 'puerto-vallarta-mexico-by-utmb-nakawe-53k-2027-utmb-32458', 'Puerto Vallarta México by UTMB - Nakawé 53K', date '2027-03-05', 'Malecón Puerto Vallarta, Mexico', 53, 2500, 'https://puerto-vallarta.utmb.world/races/Nakawe', 'solo'),
  ('puerto-vallarta', 32456, 'puerto-vallarta-mexico-by-utmb-hikuri-81k-2027-utmb-32456', 'Puerto Vallarta México by UTMB - Hikuri 81K', date '2027-03-05', 'Malecón Puerto Vallarta, Mexico', 81, 3900, 'https://puerto-vallarta.utmb.world/races/Hikuri', 'solo'),
  ('xtrail', 54978, 'xtrail-kenting-by-utmb-xtrail-50k-2027-utmb-54978', 'Xtrail Kenting by UTMB - Xtrail 50K', date '2027-03-06', 'Howard Beach Resort Kenting, Chinese Taipei', 50, 1496, 'https://xtrail.utmb.world/races/Top-50K', 'solo'),
  ('xtrail', 54976, 'xtrail-kenting-by-utmb-xtrail-100k-2027-utmb-54976', 'Xtrail Kenting by UTMB - Xtrail 100K', date '2027-03-06', 'Howard Beach Resort Kenting, Chinese Taipei', 98, 3291, 'https://xtrail.utmb.world/races/Top-100K', 'solo'),
  ('puerto-vallarta', 39602, 'puerto-vallarta-mexico-by-utmb-pata-salada-5k-2027-utmb-39602', 'Puerto Vallarta México by UTMB - Pata Salada 5K', date '2027-03-06', 'Malecón Puerto Vallarta, Mexico', 5, 200, 'https://puerto-vallarta.utmb.world/races/PataSalada', 'solo'),
  ('puerto-vallarta', 39600, 'puerto-vallarta-mexico-by-utmb-haramara-37k-2027-utmb-39600', 'Puerto Vallarta México by UTMB - Haramara 37K', date '2027-03-06', 'Malecón Puerto Vallarta, Mexico', 37, 1600, 'https://puerto-vallarta.utmb.world/races/Haramara', 'solo'),
  ('puerto-vallarta', 32460, 'puerto-vallarta-mexico-by-utmb-ereno-20k-2027-utmb-32460', 'Puerto Vallarta México by UTMB - Ereno 20K', date '2027-03-06', 'Canopy River Park, Mexico', 20, 1050, 'https://puerto-vallarta.utmb.world/races/Ereno', 'solo'),
  ('xtrail', 54982, 'xtrail-kenting-by-utmb-xtrail-10k-2027-utmb-54982', 'Xtrail Kenting by UTMB - Xtrail 10K', date '2027-03-07', 'Howard Beach Resort Kenting, Chinese Taipei', 11, 201, 'https://xtrail.utmb.world/races/Top-10K', 'solo'),
  ('xtrail', 54980, 'xtrail-kenting-by-utmb-xtrail-25k-2027-utmb-54980', 'Xtrail Kenting by UTMB - Xtrail 25K', date '2027-03-07', 'Howard Beach Resort Kenting, Chinese Taipei', 26, 589, 'https://xtrail.utmb.world/races/Top-25K', 'solo'),
  ('chianti', 29671, 'chianti-ultra-trail-by-utmb-chianti-marathon-trail-2027-utmb-29671', 'Chianti Ultra Trail by UTMB® - Chianti Marathon Trail', date '2027-03-19', 'Castellina in Chianti , Italy', 46, 1650, 'https://chianti.utmb.world/races/CMT', 'solo'),
  ('chianti', 29670, 'chianti-ultra-trail-by-utmb-chianti-ultra-trail-2027-utmb-29670', 'Chianti Ultra Trail by UTMB® - Chianti Ultra Trail', date '2027-03-20', 'Radda in Chianti, Italy', 73, 3000, 'https://chianti.utmb.world/races/CUT', 'solo'),
  ('chianti', 29669, 'chianti-ultra-trail-by-utmb-ultra-trail-chianti-castles-2027-utmb-29669', 'Chianti Ultra Trail by UTMB® - Ultra Trail Chianti Castles', date '2027-03-20', 'Radda in Chianti, Italy', 123, 5200, 'https://chianti.utmb.world/races/UTCC', 'solo'),
  ('chianti', 42634, 'chianti-ultra-trail-by-utmb-chianti-wine-run-2027-utmb-42634', 'Chianti Ultra Trail by UTMB® - Chianti Wine Run', date '2027-03-21', 'Radda in Chianti , Italy', 10, 400, 'https://chianti.utmb.world/races/CWR', 'solo'),
  ('chianti', 29672, 'chianti-ultra-trail-by-utmb-chianti-half-trail-2027-utmb-29672', 'Chianti Ultra Trail by UTMB® - Chianti Half Trail', date '2027-03-21', 'Gaiole in Chianti, Italy', 20, 920, 'https://chianti.utmb.world/races/CHT', 'solo'),
  ('istria', 1572, 'istria-100-by-utmb-168k-2027-utmb-1572', 'Istria 100 by UTMB®️ - 168K', date '2027-04-02', 'Labin, Croatia', 168, 6800, 'https://istria.utmb.world/races/168K', 'solo'),
  ('jujuy', 65504, 'jujuy-fuerza-sagrada-by-utmb-amaru-21k-2027-utmb-65504', 'Jujuy Fuerza Sagrada by UTMB - AMARU 21K', date '2027-04-03', 'INCAHUASI, Argentina', 21.3, 884, 'https://jujuy.utmb.world/races/AMARU', 'solo'),
  ('jujuy', 65502, 'jujuy-fuerza-sagrada-by-utmb-wayra-35k-2027-utmb-65502', 'Jujuy Fuerza Sagrada by UTMB - WAYRA 35K', date '2027-04-03', 'INCAHUASI, Argentina', 34, 1826, 'https://jujuy.utmb.world/races/WAYRA', 'solo'),
  ('jujuy', 65498, 'jujuy-fuerza-sagrada-by-utmb-kuntur-50k-2027-utmb-65498', 'Jujuy Fuerza Sagrada by UTMB - KUNTUR 50K', date '2027-04-03', 'INCAHUASI, Argentina', 50.3, 2754, 'https://jujuy.utmb.world/races/KUNTUR', 'solo'),
  ('jujuy', 65496, 'jujuy-fuerza-sagrada-by-utmb-inti-88k-2027-utmb-65496', 'Jujuy Fuerza Sagrada by UTMB - INTI 88K', date '2027-04-03', 'Tilcara, Argentina', 87.2, 5101, 'https://jujuy.utmb.world/races/INTI', 'solo'),
  ('istria', 4017, 'istria-100-by-utmb-42k-2027-utmb-4017', 'Istria 100 by UTMB®️ - 42K', date '2027-04-03', 'Motovun, Croatia', 42, 1000, 'https://istria.utmb.world/races/42K', 'solo'),
  ('istria', 2318, 'istria-100-by-utmb-69k-2027-utmb-2318', 'Istria 100 by UTMB®️ - 69K', date '2027-04-03', 'Buzet, Croatia', 69.6, 2400, 'https://istria.utmb.world/races/69K', 'solo'),
  ('istria', 1573, 'istria-100-by-utmb-110k-2027-utmb-1573', 'Istria 100 by UTMB®️ - 110K', date '2027-04-03', 'Buzet, Croatia', 111, 4200, 'https://istria.utmb.world/races/110K', 'solo'),
  ('jujuy', 65508, 'jujuy-fuerza-sagrada-by-utmb-pukara-5k-2027-utmb-65508', 'Jujuy Fuerza Sagrada by UTMB - PUKARA 5K', date '2027-04-04', 'PURMAMARCA, Argentina', 4.5, 175, 'https://jujuy.utmb.world/races/PUKARA', 'solo'),
  ('jujuy', 65506, 'jujuy-fuerza-sagrada-by-utmb-rumi-12k-2027-utmb-65506', 'Jujuy Fuerza Sagrada by UTMB - RUMI 12K', date '2027-04-04', 'PURMAMARCA, Argentina', 11.9, 723, 'https://jujuy.utmb.world/races/RUMI', 'solo'),
  ('istria', 20687, 'istria-100-by-utmb-21k-2027-utmb-20687', 'Istria 100 by UTMB®️ - 21K', date '2027-04-04', 'Grožnjan , Croatia', 21.5, 157, 'https://istria.utmb.world/races/21K', 'solo'),
  ('tenerife', 45960, 'tenerife-bluetrail-by-utmb-vertical-night-challenge-2027-utmb-45960', 'Tenerife Bluetrail by UTMB - VERTICAL NIGHT CHALLENGE', date '2027-04-08', 'PLAYA DEL SOCORRO, Spain', 6.5, 850, 'https://tenerife.utmb.world/races/tbt-VK', 'solo'),
  ('tenerife', 62720, 'tenerife-bluetrail-by-utmb-tenerife-bluetrail-68k-2027-utmb-62720', 'Tenerife Bluetrail by UTMB - TENERIFE BLUETRAIL 68k', date '2027-04-09', 'LA ESPERANZA, Spain', 68, 3600, 'https://tenerife.utmb.world/races/tbt-100K-68k', 'solo'),
  ('tenerife', 946, 'tenerife-bluetrail-by-utmb-tenerife-bluetrail-110k-2027-utmb-946', 'Tenerife Bluetrail by UTMB - TENERIFE BLUETRAIL 110k', date '2027-04-09', 'PLAYA DE LOS CRISTIANOS , Spain', 110, 6250, 'https://tenerife.utmb.world/races/tbt-100M', 'solo'),
  ('hiroshima', 64426, 'hiroshima-ultra-trail-by-utmb-hiroshima-50k-2027-utmb-64426', 'Hiroshima Ultra-Trail by UTMB - HIROSHIMA 50K', date '2027-04-10', 'Hiroshima Gate Park, Japan', 48.76, 2755, 'https://hiroshima.utmb.world/races/HIROSHIMA50K', 'solo'),
  ('hiroshima', 64424, 'hiroshima-ultra-trail-by-utmb-hiroshima-100k-2027-utmb-64424', 'Hiroshima Ultra-Trail by UTMB - HIROSHIMA 100K', date '2027-04-10', 'Hiroshima Gate Park, Japan', 94.68, 5587, 'https://hiroshima.utmb.world/races/HIROSHIMA100K', 'solo'),
  ('desertrats', 37036, 'desert-rats-trail-running-festival-by-utmb-50k-2027-utmb-37036', 'Desert RATS Trail Running Festival by UTMB - 50K', date '2027-04-10', 'Fruita CO, Mack Exit, Hawkeye Trailhead, United States of America', 48, 1050, 'https://desertrats.utmb.world/races/50K', 'solo'),
  ('tenerife', 22799, 'tenerife-bluetrail-by-utmb-tenerife-bluetrail-47k-relay-2027-utmb-22799', 'Tenerife Bluetrail by UTMB - TENERIFE BLUETRAIL 47k RELAY', date '2027-04-10', 'PINOLERE, Spain', 47, 2600, 'https://tenerife.utmb.world/races/tbt-relay-50K', 'relay'),
  ('tenerife', 6081, 'tenerife-bluetrail-by-utmb-tenerife-bluetrail-47k-2027-utmb-6081', 'Tenerife Bluetrail by UTMB - TENERIFE BLUETRAIL 47k', date '2027-04-10', 'PINOLERE, Spain', 47, 2600, 'https://tenerife.utmb.world/races/tbt-50K', 'solo'),
  ('tenerife', 1953, 'tenerife-bluetrail-by-utmb-tenerife-bluetrail-24k-2027-utmb-1953', 'Tenerife Bluetrail by UTMB - TENERIFE BLUETRAIL 24k', date '2027-04-10', 'PALO BLANCO, Spain', 24, 1300, 'https://tenerife.utmb.world/races/tbt-20K', 'solo'),
  ('desertrats', 1047, 'desert-rats-trail-running-festival-by-utmb-100k-2027-utmb-1047', 'Desert RATS Trail Running Festival by UTMB - 100K', date '2027-04-10', 'Fruita CO, Mack Exit, Hawkeye Trailhead, United States of America', 100, 2050, 'https://desertrats.utmb.world/races/100K', 'solo'),
  ('tenerife', 945, 'tenerife-bluetrail-by-utmb-tenerife-bluetrail-82k-2027-utmb-945', 'Tenerife Bluetrail by UTMB - TENERIFE BLUETRAIL 82k', date '2027-04-10', 'VILAFLOR, Spain', 82, 3300, 'https://tenerife.utmb.world/races/tbt-100K', 'solo'),
  ('hiroshima', 64428, 'hiroshima-ultra-trail-by-utmb-hiroshima-25k-2027-utmb-64428', 'Hiroshima Ultra-Trail by UTMB - HIROSHIMA 25K', date '2027-04-11', 'Hiroshima Gate Park, Japan', 24.4, 873, 'https://hiroshima.utmb.world/races/HIROSHIMA25K', 'solo'),
  ('desertrats', 39144, 'desert-rats-trail-running-festival-by-utmb-10k-2027-utmb-39144', 'Desert RATS Trail Running Festival by UTMB - 10K', date '2027-04-11', 'Fruita CO, Mack Exit, Hawkeye Trailhead, United States of America', 9, 200, 'https://desertrats.utmb.world/races/10K', 'solo'),
  ('desertrats', 31091, 'desert-rats-trail-running-festival-by-utmb-21k-2027-utmb-31091', 'Desert RATS Trail Running Festival by UTMB - 21K', date '2027-04-11', 'Fruita CO, Mack Exit, Hawkeye Trailhead, United States of America', 21, 700, 'https://desertrats.utmb.world/races/21k', 'solo'),
  ('canyons', 33574, 'the-canyons-endurance-runs-by-utmb-100m-2027-utmb-33574', 'The Canyons Endurance Runs by UTMB® - 100M', date '2027-04-23', 'China Wall Trailhead, United States of America', 161, 5550, 'https://canyons.utmb.world/races/100M', 'solo'),
  ('canyons', 9087, 'the-canyons-endurance-runs-by-utmb-25k-2027-utmb-9087', 'The Canyons Endurance Runs by UTMB® - 25K', date '2027-04-23', 'Downtown Auburn, United States of America', 25, 850, 'https://canyons.utmb.world/races/25K', 'solo'),
  ('ventoux', 133, 'grand-raid-ventoux-by-utmb-ultra-geant-de-provence-ugp-2027-utmb-133', 'Grand Raid Ventoux by UTMB - Ultra Géant de Provence - UGP', date '2027-04-23', 'Malaucène, France', 125, 5700, 'https://ventoux.utmb.world/races/GRV100M', 'solo'),
  ('ventoux', 42922, 'grand-raid-ventoux-by-utmb-trail-des-coteaux-tdc-2027-utmb-42922', 'Grand Raid Ventoux by UTMB - Trail des Coteaux - TDC', date '2027-04-24', 'Malaucène, France', 26, 1100, 'https://ventoux.utmb.world/races/GRV20K', 'solo'),
  ('ventoux', 42918, 'grand-raid-ventoux-by-utmb-grande-epopee-ventoux-gev-2027-utmb-42918', 'Grand Raid Ventoux by UTMB - Grande Epopée Ventoux - GEV', date '2027-04-24', 'Malaucène, France', 87, 4200, 'https://ventoux.utmb.world/races/GRV100K', 'solo'),
  ('canyons', 3753, 'the-canyons-endurance-runs-by-utmb-100k-2027-utmb-3753', 'The Canyons Endurance Runs by UTMB® - 100K', date '2027-04-24', 'China Wall Trailhead, United States of America', 100, 3750, 'https://canyons.utmb.world/races/100K', 'solo'),
  ('canyons', 2983, 'the-canyons-endurance-runs-by-utmb-50k-2027-utmb-2983', 'The Canyons Endurance Runs by UTMB® - 50K', date '2027-04-24', 'Downtown Auburn, United States of America', 50, 1700, 'https://canyons.utmb.world/races/50K', 'solo'),
  ('ventoux', 42920, 'grand-raid-ventoux-by-utmb-mistral-marathon-trail-mmt-2027-utmb-42920', 'Grand Raid Ventoux by UTMB - Mistral Marathon Trail - MMT', date '2027-04-25', 'Malaucène, France', 51, 2500, 'https://ventoux.utmb.world/races/GRV50K', 'solo'),
  ('ohmeudeus', 14089, 'oh-meu-deus-by-utmb-oh-meu-deus-50k-2027-utmb-14089', 'Oh Meu Deus by UTMB - Oh Meu Deus 50K', date '2027-04-30', 'Loriga, Portugal', 52, 2900, 'https://ohmeudeus.utmb.world/races/omd50k', 'solo'),
  ('ohmeudeus', 1858, 'oh-meu-deus-by-utmb-oh-meu-deus-100m-2027-utmb-1858', 'Oh Meu Deus by UTMB - Oh Meu Deus 100M', date '2027-04-30', 'To be defined, Portugal', 167, 8900, 'https://ohmeudeus.utmb.world/races/omd100m', 'solo'),
  ('ohmeudeus', 1022, 'oh-meu-deus-by-utmb-oh-meu-deus-100k-2027-utmb-1022', 'Oh Meu Deus by UTMB - Oh Meu Deus 100K', date '2027-05-01', 'Seia, Portugal', 94, 5300, 'https://ohmeudeus.utmb.world/races/omd100k', 'solo'),
  ('ohmeudeus', 29552, 'oh-meu-deus-by-utmb-oh-meu-deus-20k-2027-utmb-29552', 'Oh Meu Deus by UTMB - Oh Meu Deus 20K', date '2027-05-02', 'São Romão, Portugal', 22, 1000, 'https://ohmeudeus.utmb.world/races/omd20k', 'solo'),
  ('uta', 36798, 'hoka-ultra-trail-australia-by-utmb-uta11-2027-utmb-36798', 'HOKA Ultra-Trail Australia by UTMB - UTA11', date '2027-05-13', 'Scenic World, Katoomba, Australia', 11.4, 731, 'https://uta.utmb.world/races/UTA11', 'solo'),
  ('uta', 49644, 'hoka-ultra-trail-australia-by-utmb-utamiler-2027-utmb-49644', 'HOKA Ultra-Trail Australia by UTMB - UTAMiler', date '2027-05-14', 'Govetts Leap Carpark, Blackheath, Australia', 161.1, 7200, 'https://uta.utmb.world/races/UTAMiler', 'solo'),
  ('alsace', 35488, 'trail-alsace-by-utmb-ultra-trail-des-paiens-2027-utmb-35488', 'Trail Alsace by UTMB - Ultra-Trail des Païens', date '2027-05-14', 'Orschwiller, France', 108, 3900, 'https://alsace.utmb.world/races/UTDP', 'solo'),
  ('alsace', 35486, 'trail-alsace-by-utmb-ultra-trail-des-chevaliers-2027-utmb-35486', 'Trail Alsace by UTMB - Ultra-Trail des Chevaliers', date '2027-05-14', 'Station du Lac Blanc, massif des Vosges, France', 158, 5100, 'https://alsace.utmb.world/races/UTDC', 'solo'),
  ('uta', 6289, 'hoka-ultra-trail-australia-by-utmb-uta22-2027-utmb-6289', 'HOKA Ultra-Trail Australia by UTMB - UTA22', date '2027-05-14', 'Queen Victoria Hospital, Australia', 22, 1200, 'https://uta.utmb.world/races/UTA22', 'solo'),
  ('alsace', 59510, 'trail-alsace-by-utmb-trail-des-ecuyers-cadets-2027-utmb-59510', 'Trail Alsace by UTMB - TRAIL DES ECUYERS Cadets', date '2027-05-15', 'Obernai, France', 10.5, 400, 'https://alsace.utmb.world/races', 'solo'),
  ('alsace', 59508, 'trail-alsace-by-utmb-trail-des-ecuyers-2027-utmb-59508', 'Trail Alsace by UTMB - Trail des Ecuyers', date '2027-05-15', 'Châtenois, France', 10.5, 400, 'https://alsace.utmb.world/races/TDE', 'solo'),
  ('rothrock', 58026, 'rothrock-by-utmb-50k-2027-utmb-58026', 'Rothrock by UTMB - 50K', date '2027-05-15', 'Tussey Mountain Ski and Recreation, United States of America', 53.3, 1550, 'https://rothrock.utmb.world/races/50K', 'solo'),
  ('alsace', 50844, 'trail-alsace-by-utmb-ronde-des-pages-2027-utmb-50844', 'Trail Alsace by UTMB - Ronde des Pages', date '2027-05-15', 'Obernai, France', 18, 250, 'https://alsace.utmb.world/races/RDP', 'solo'),
  ('alsace', 35484, 'trail-alsace-by-utmb-trail-des-pelerins-2027-utmb-35484', 'Trail Alsace by UTMB - Trail des Pèlerins', date '2027-05-15', 'Barr, France', 29, 800, 'https://alsace.utmb.world/races/TDP', 'solo'),
  ('uta', 1723, 'hoka-ultra-trail-australia-by-utmb-uta50-2027-utmb-1723', 'HOKA Ultra-Trail Australia by UTMB - UTA50', date '2027-05-15', 'Scenic World, Katoomba, Australia', 51, 2400, 'https://uta.utmb.world/races/UTA50', 'solo'),
  ('uta', 1030, 'hoka-ultra-trail-australia-by-utmb-uta100-2027-utmb-1030', 'HOKA Ultra-Trail Australia by UTMB - UTA100', date '2027-05-15', 'Scenic World, Katoomba, Australia', 101, 4400, 'https://uta.utmb.world/races/UTA100', 'solo'),
  ('rothrock', 58028, 'rothrock-by-utmb-25k-2027-utmb-58028', 'Rothrock by UTMB - 25K', date '2027-05-16', 'Tussey Mountain Ski & Recreation, United States of America', 26.9, 1188, 'https://rothrock.utmb.world/races/25K', 'solo'),
  ('alsace', 35482, 'trail-alsace-by-utmb-trail-des-celtes-2027-utmb-35482', 'Trail Alsace by UTMB - Trail des Celtes', date '2027-05-16', 'Barr, France', 47, 1600, 'https://alsace.utmb.world/races/TDC', 'solo'),
  ('mut', 36618, 'mountain-ultra-trail-by-utmb-mut-miler-by-utmb-2027-utmb-36618', 'Mountain Ultra Trail by UTMB® - MUT Miler by UTMB', date '2027-05-28', 'Outeniqua Stadium, George, South Africa', 168, 8014, 'https://mut.utmb.world/races/mutmiler', 'solo'),
  ('mut', 33612, 'mountain-ultra-trail-by-utmb-mut-marathon-by-utmb-2027-utmb-33612', 'Mountain Ultra Trail by UTMB® - MUT Marathon by UTMB', date '2027-05-29', 'George, South Africa', 43, 2312, 'https://mut.utmb.world/races/mut45', 'solo'),
  ('mut', 33610, 'mountain-ultra-trail-by-utmb-mut-60-by-utmb-2027-utmb-33610', 'Mountain Ultra Trail by UTMB® - MUT 60 by UTMB', date '2027-05-29', 'George, South Africa', 58, 3005, 'https://mut.utmb.world/races/mut60', 'solo'),
  ('mut', 33608, 'mountain-ultra-trail-by-utmb-mut-100-by-utmb-2027-utmb-33608', 'Mountain Ultra Trail by UTMB® - MUT 100 by UTMB', date '2027-05-29', 'George, South Africa', 100, 4717, 'https://mut.utmb.world/races/mut100', 'solo'),
  ('mut', 39662, 'mountain-ultra-trail-by-utmb-mut-lite-2027-utmb-39662', 'Mountain Ultra Trail by UTMB® - MUT Lite', date '2027-05-30', 'George, South Africa', 11, 260, 'https://mut.utmb.world/races', 'solo'),
  ('mut', 33614, 'mountain-ultra-trail-by-utmb-mut-challenge-by-utmb-2027-utmb-33614', 'Mountain Ultra Trail by UTMB® - MUT Challenge by UTMB', date '2027-05-30', 'George, South Africa', 25, 1043, 'https://mut.utmb.world/races/mutchallenge', 'solo'),
  ('chattanooga', 64662, 'ultra-trail-chattanooga-by-utmb-50k-2027-utmb-64662', 'Ultra Trail Chattanooga by UTMB - 50K', date '2027-06-05', 'Chattanooga, TN, Erlanger Park, United States of America', 31.4, 3818, 'https://chattanooga.utmb.world/races/50K', 'solo'),
  ('chattanooga', 64660, 'ultra-trail-chattanooga-by-utmb-100k-2027-utmb-64660', 'Ultra Trail Chattanooga by UTMB - 100K', date '2027-06-05', 'Chattanooga TN, Erlanger Park, United States of America', 100, 7995, 'https://chattanooga.utmb.world/races/100K', 'solo'),
  ('mozart', 27503, 'mozart-100-by-utmb-mozart-lake-trail-2027-utmb-27503', 'mozart 100 by UTMB - mozart Lake Trail', date '2027-06-05', 'Fuschl am See, Austria', 12, 200, 'https://mozart.utmb.world/races/mozartlake', 'solo'),
  ('mozart', 12703, 'mozart-100-by-utmb-mozart-half-marathon-2027-utmb-12703', 'mozart 100 by UTMB - mozart Half Marathon', date '2027-06-05', 'Koppl, Austria', 28, 1100, 'https://mozart.utmb.world/races/mozarthalf', 'solo'),
  ('mozart', 8817, 'mozart-100-by-utmb-mozart-marathon-2027-utmb-8817', 'mozart 100 by UTMB - mozart Marathon', date '2027-06-05', 'Faistenau, Austria', 44, 1600, 'https://mozart.utmb.world/races/mozartmarathon', 'solo'),
  ('mozart', 1682, 'mozart-100-by-utmb-mozart-ultra-2027-utmb-1682', 'mozart 100 by UTMB - mozart Ultra', date '2027-06-05', 'St. Gilgen, Austria', 84, 4800, 'https://mozart.utmb.world/races/mozartultra', 'solo'),
  ('mozart', 1604, 'mozart-100-by-utmb-mozart-100-2027-utmb-1604', 'mozart 100 by UTMB - mozart 100', date '2027-06-05', 'Fuschl am See, Austria', 119, 6000, 'https://mozart.utmb.world/races/mozart100', 'solo'),
  ('chattanooga', 64664, 'ultra-trail-chattanooga-by-utmb-20k-2027-utmb-64664', 'Ultra Trail Chattanooga by UTMB - 20K', date '2027-06-06', 'Chattanooga, TN, Erlanger Park, United States of America', 12.8, 1348, 'https://chattanooga.utmb.world/races/20k', 'solo'),
  ('andorra', 41432, 'trail-100-andorra-by-utmb-trail-80k-2027-utmb-41432', 'Trail 100 Andorra by UTMB® - Trail 80K', date '2027-06-11', 'Ordino, Andorra', 79, 3900, 'https://andorra.utmb.world/races/Trail-80k', 'solo'),
  ('andorra', 27492, 'trail-100-andorra-by-utmb-trail-50k-2027-utmb-27492', 'Trail 100 Andorra by UTMB® - Trail 50K', date '2027-06-12', 'Ordino, Andorra', 50, 3400, 'https://andorra.utmb.world/races/Trail-50K', 'solo'),
  ('andorra', 27471, 'trail-100-andorra-by-utmb-ultra-105k-2027-utmb-27471', 'Trail 100 Andorra by UTMB® - Ultra 105K', date '2027-06-12', 'Ordino, Andorra', 105, 6800, 'https://andorra.utmb.world/races/Ultra-105K', 'solo'),
  ('andorra', 41468, 'trail-100-andorra-by-utmb-trail-10km-2027-utmb-41468', 'Trail 100 Andorra by UTMB® - Trail 10Km', date '2027-06-13', 'Ordino, Andorra', 10, 500, 'https://andorra.utmb.world/races/Trail-10k', 'solo'),
  ('andorra', 27494, 'trail-100-andorra-by-utmb-trail-21k-2027-utmb-27494', 'Trail 100 Andorra by UTMB® - Trail 21K', date '2027-06-13', 'Ordino, Andorra', 24.9, 1350, 'https://andorra.utmb.world/races/Trail-21K', 'solo'),
  ('zugspitz', 56650, 'zugspitz-ultra-trail-by-utmb-zut100-2027-utmb-56650', 'Zugspitz Ultra Trail by UTMB - ZUT100', date '2027-06-17', 'Garmisch-Partenkirchen, Germany', 167, 8205, 'https://zugspitz.utmb.world/races/zut100', 'solo'),
  ('zugspitz', 56636, 'zugspitz-ultra-trail-by-utmb-garmisch-partenkirchen-trail-2027-utmb-56636', 'Zugspitz Ultra Trail by UTMB - Garmisch-Partenkirchen Trail', date '2027-06-18', 'Garmisch-Partenkirchen, Germany', 29, 1565, 'https://zugspitz.utmb.world/races/garmisch-partenkirchen-trail', 'solo'),
  ('zugspitz', 56630, 'zugspitz-ultra-trail-by-utmb-ehrwald-trail-2027-utmb-56630', 'Zugspitz Ultra Trail by UTMB - Ehrwald Trail', date '2027-06-18', 'Ehrwald, Germany', 86, 4295, 'https://zugspitz.utmb.world/races/ehrwald-trail', 'solo'),
  ('zugspitz', 56628, 'zugspitz-ultra-trail-by-utmb-ultratrail-2027-utmb-56628', 'Zugspitz Ultra Trail by UTMB - Ultratrail', date '2027-06-18', 'Garmisch-Partenkirchen, Germany', 107, 5280, 'https://zugspitz.utmb.world/races/ultratrail', 'solo'),
  ('saint-jacques', 4510, 'trail-du-saint-jacques-by-utmb-ultra-du-saint-jacques-100m-2027-utmb-4510', 'Trail du Saint-Jacques by UTMB® - Ultra du Saint Jacques - 100M', date '2027-06-18', 'Saugues, France', 140, 6000, 'https://saint-jacques.utmb.world/races/100M', 'solo'),
  ('zugspitz', 56640, 'zugspitz-ultra-trail-by-utmb-grainau-trail-2027-utmb-56640', 'Zugspitz Ultra Trail by UTMB - Grainau Trail', date '2027-06-19', 'Grainau, Germany', 16, 760, 'https://zugspitz.utmb.world/races/grainau-trail', 'solo'),
  ('zugspitz', 56634, 'zugspitz-ultra-trail-by-utmb-mittenwald-trail-2027-utmb-56634', 'Zugspitz Ultra Trail by UTMB - Mittenwald Trail', date '2027-06-19', 'Mittenwald, Germany', 44, 2110, 'https://zugspitz.utmb.world/races/mittenwald-trail', 'solo'),
  ('zugspitz', 56632, 'zugspitz-ultra-trail-by-utmb-leutasch-trail-2027-utmb-56632', 'Zugspitz Ultra Trail by UTMB - Leutasch Trail', date '2027-06-19', 'Leutasch, Germany', 68.5, 3100, 'https://zugspitz.utmb.world/races/leutasch-trail', 'solo'),
  ('saint-jacques', 51128, 'trail-du-saint-jacques-by-utmb-le-12-du-dolaizon-2027-utmb-51128', 'Trail du Saint-Jacques by UTMB® - Le 12 du Dolaizon', date '2027-06-19', 'Saint-Christophe-sur-Dolaizon, France', 12, 200, 'https://saint-jacques.utmb.world/races/Le-12-du-Dolaizon', 'solo'),
  ('saint-jacques', 1231, 'trail-du-saint-jacques-by-utmb-grand-trail-du-saint-jacques-100k-2027-utmb-1231', 'Trail du Saint-Jacques by UTMB® - Grand Trail du Saint Jacques - 100K', date '2027-06-19', 'Monistrol d''Allier, France', 88, 3600, 'https://saint-jacques.utmb.world/races/100K', 'solo'),
  ('saint-jacques', 4004, 'trail-du-saint-jacques-by-utmb-monistrail-50k-2027-utmb-4004', 'Trail du Saint-Jacques by UTMB® - Monistrail - 50K', date '2027-06-20', 'Monistrol d''Allier, France', 55, 2100, 'https://saint-jacques.utmb.world/races/50K', 'solo'),
  ('saint-jacques', 4001, 'trail-du-saint-jacques-by-utmb-les-chibottes-20k-2027-utmb-4001', 'Trail du Saint-Jacques by UTMB® - Les Chibottes - 20K', date '2027-06-20', 'Solignac-sur-Loire, France', 28, 750, 'https://saint-jacques.utmb.world/races/20K', 'solo'),
  ('lavaredo', 38252, 'lavaredo-ultra-trail-by-utmb-lavaredo-10k-2027-utmb-38252', 'Lavaredo Ultra Trail by UTMB® - Lavaredo 10K', date '2027-06-23', 'Cortina d''Ampezzo, Italy', 10, 300, 'https://lavaredo.utmb.world/races/lavaredo10K', 'solo'),
  ('torrencial', 24947, 'torrencial-chilie-by-utmb-pilolcura-100k-2027-utmb-24947', 'Torrencial Chilie by UTMB - PILOLCURA 100K', date '2027-06-24', 'Punucapa, Chile', 101, 4100, 'https://torrencial.utmb.world/races/PILOLCURA100K', 'solo'),
  ('lavaredo', 3905, 'lavaredo-ultra-trail-by-utmb-lavaredo-20k-2027-utmb-3905', 'Lavaredo Ultra Trail by UTMB® - Lavaredo 20K', date '2027-06-24', 'Cortina d''Ampezzo, Italy', 20, 1000, 'https://lavaredo.utmb.world/races/lavaredo20k', 'solo'),
  ('torrencial', 13133, 'torrencial-chilie-by-utmb-oncol-65k-2027-utmb-13133', 'Torrencial Chilie by UTMB - ONCOL 65K', date '2027-06-25', 'Punucapa, Chile', 65, 2600, 'https://torrencial.utmb.world/races/ONCOL65K', 'solo'),
  ('lavaredo', 1334, 'lavaredo-ultra-trail-by-utmb-lavaredo-50k-2027-utmb-1334', 'Lavaredo Ultra Trail by UTMB® - Lavaredo 50K', date '2027-06-25', 'Cortina d’Ampezzo, Italy', 50, 2600, 'https://lavaredo.utmb.world/races/lavaredo50k', 'solo'),
  ('lavaredo', 178, 'lavaredo-ultra-trail-by-utmb-lavaredo-120k-2027-utmb-178', 'Lavaredo Ultra Trail by UTMB® - Lavaredo 120K', date '2027-06-25', 'Cortina d''Ampezzo, Italy', 120, 5800, 'https://lavaredo.utmb.world/races/lavaredo120k', 'solo'),
  ('torrencial', 53946, 'torrencial-chilie-by-utmb-isla-teja-6k-2027-utmb-53946', 'Torrencial Chilie by UTMB - ISLA TEJA 6K', date '2027-06-26', 'Parque Saval, Valdivia, Chile', 6.5, 200, 'https://torrencial.utmb.world/races/TEJA6K', 'solo'),
  ('torrencial', 53944, 'torrencial-chilie-by-utmb-cau-cau-12k-nocturno-2027-utmb-53944', 'Torrencial Chilie by UTMB - CAU CAU 12K NOCTURNO', date '2027-06-26', 'Parque Saval, Valdivia, Chile', 12, 400, 'https://torrencial.utmb.world/races/CAUCAU12K', 'solo'),
  ('lavaredo', 15547, 'lavaredo-ultra-trail-by-utmb-lavaredo-80k-2027-utmb-15547', 'Lavaredo Ultra Trail by UTMB® - Lavaredo 80K', date '2027-06-26', 'Val Marzon Auronzo di Cadore, Italy', 80, 4600, 'https://lavaredo.utmb.world/races/lavaredo80k', 'solo'),
  ('torrencial', 14479, 'torrencial-chilie-by-utmb-collico-20k-2027-utmb-14479', 'Torrencial Chilie by UTMB - COLLICO 20K', date '2027-06-27', 'Collico, Chile', 20, 800, 'https://torrencial.utmb.world/races/COLLICO20K', 'solo'),
  ('torrencial', 14477, 'torrencial-chilie-by-utmb-llancahue-45k-2027-utmb-14477', 'Torrencial Chilie by UTMB - LLANCAHUE 45K', date '2027-06-27', 'Collico, Chile', 45, 1600, 'https://torrencial.utmb.world/races/LLANCAHUE45K', 'solo'),
  ('valdaran', 55752, 'hoka-val-d-aran-by-utmb-termieres-dera-libertat-tdl-2027-utmb-55752', 'HOKA Val d’Aran by UTMB® - Termières dera Libertat - TDL', date '2027-07-07', 'BOSSÒST, Spain', 75, 5100, 'https://valdaran.utmb.world/races/TDL', 'solo'),
  ('valdaran', 53582, 'hoka-val-d-aran-by-utmb-vielha-10k-2027-utmb-53582', 'HOKA Val d’Aran by UTMB® - VIELHA 10K', date '2027-07-07', 'VIELHA, Spain', 10, 500, 'https://valdaran.utmb.world/races/10K', 'solo'),
  ('valdaran', 21261, 'hoka-val-d-aran-by-utmb-peades-d-aigua-pda-2027-utmb-21261', 'HOKA Val d’Aran by UTMB® - Peades d''Aigua - PDA', date '2027-07-08', 'SALARDÚ, Spain', 55, 3300, 'https://valdaran.utmb.world/races/PDA', 'solo'),
  ('verbier', 65334, 'trail-verbier-st-bernard-by-utmb-verbier-marathon-2027-utmb-65334', 'Trail Verbier St Bernard by UTMB - Verbier Marathon', date '2027-07-09', 'Moay (Bruson) , Switzerland', 47, 2900, 'https://verbier.utmb.world/races/verbier-marathon', 'solo'),
  ('valdaran', 21263, 'hoka-val-d-aran-by-utmb-torn-dera-val-d-aran-vda-2027-utmb-21263', 'HOKA Val d’Aran by UTMB® - Torn dera Val d''Aran - VDA', date '2027-07-09', 'VIELHA, Spain', 163, 10000, 'https://valdaran.utmb.world/races/VDA', 'solo'),
  ('valdaran', 21259, 'hoka-val-d-aran-by-utmb-camins-d-her-cdh-2027-utmb-21259', 'HOKA Val d’Aran by UTMB® - Camins d''Hèr - CDH', date '2027-07-09', 'LES, Spain', 110, 6400, 'https://valdaran.utmb.world/races/CDH', 'solo'),
  ('verbier', 10441, 'trail-verbier-st-bernard-by-utmb-verbier-marathon-x-treme-2027-utmb-10441', 'Trail Verbier St Bernard by UTMB - Verbier Marathon X-Treme', date '2027-07-09', 'Moay (Bruson) , Switzerland', 43, 3000, 'https://verbier.utmb.world/races/Verbier-marathon-Xtreme', 'solo'),
  ('verbier', 669, 'trail-verbier-st-bernard-by-utmb-x-alpine-2027-utmb-669', 'Trail Verbier St Bernard by UTMB - X-Alpine', date '2027-07-09', 'Verbier, Switzerland', 140, 9300, 'https://verbier.utmb.world/races/X-Alpine', 'solo'),
  ('valdaran', 34470, 'hoka-val-d-aran-by-utmb-sky-18k-promesas-2027-utmb-34470', 'HOKA Val d’Aran by UTMB® - SKY 18K PROMESAS', date '2027-07-10', 'PLA DE BERET, Spain', 18, 900, 'https://valdaran.utmb.world/races/SKYP', 'solo'),
  ('valdaran', 25437, 'hoka-val-d-aran-by-utmb-sky-baqueira-beret-2027-utmb-25437', 'HOKA Val d’Aran by UTMB® - SKY - Baqueira Beret', date '2027-07-10', 'PLA DE BERET, Spain', 18, 900, 'https://valdaran.utmb.world/races/SKY', 'solo'),
  ('verbier', 10439, 'trail-verbier-st-bernard-by-utmb-x-traversee-2027-utmb-10439', 'Trail Verbier St Bernard by UTMB - X-Traversee', date '2027-07-10', 'La Fouly, Switzerland', 77, 5300, 'https://verbier.utmb.world/races/x-traversee', 'solo'),
  ('verbier', 30857, 'trail-verbier-st-bernard-by-utmb-verbier-x-plore-2027-utmb-30857', 'Trail Verbier St Bernard by UTMB - Verbier X-Plore', date '2027-07-11', 'Verbier, Switzerland', 28, 1700, 'https://verbier.utmb.world/races/X-Plore', 'solo'),
  ('eiger', 32274, 'eiger-ultra-trail-by-utmb-e250-unesco-trail-2027-utmb-32274', 'Eiger Ultra Trail® by UTMB - E250 - UNESCO Trail', date '2027-07-14', 'Grindelwald, Switzerland', 261, 18000, 'https://eiger.utmb.world/races/E250', 'solo'),
  ('mrww', 64690, 'monte-rosa-walserwaeg-by-utmb-gressoney-lys-trail-2027-utmb-64690', 'Monte Rosa WalserWaeg by UTMB - Gressoney Lys Trail', date '2027-07-16', 'Gressoney-La-Trinité, Italy', 35, 1800, 'https://mrww.utmb.world/races/GLT', 'solo'),
  ('mrww', 47114, 'monte-rosa-walserwaeg-by-utmb-les-sentiers-des-valdotains-2027-utmb-47114', 'Monte Rosa WalserWaeg by UTMB - Les sentiers des Valdôtains', date '2027-07-16', 'Aosta, Italy', 120, 8200, 'https://mrww.utmb.world/races/SDV', 'solo'),
  ('eiger', 36020, 'eiger-ultra-trail-by-utmb-kids-race-2027-utmb-36020', 'Eiger Ultra Trail® by UTMB - Kids Race', date '2027-07-16', 'Grindelwald, Switzerland', 0.35, 100, 'https://eiger.utmb.world/races/kids-race', 'solo'),
  ('eiger', 36018, 'eiger-ultra-trail-by-utmb-trail-surprise-2027-utmb-36018', 'Eiger Ultra Trail® by UTMB - Trail Surprise', date '2027-07-16', 'Grindelwald, Switzerland', 15, 800, 'https://eiger.utmb.world/races/trail-surprise', 'solo'),
  ('mrww', 31228, 'monte-rosa-walserwaeg-by-utmb-monte-rosa-trail-2027-utmb-31228', 'Monte Rosa WalserWaeg by UTMB - Monte Rosa Trail', date '2027-07-16', 'Pont-Saint-Martin, Italy', 82, 6300, 'https://mrww.utmb.world/races/MRT', 'solo'),
  ('mrww', 31229, 'monte-rosa-walserwaeg-by-utmb-walserwaeg-trail-2027-utmb-31229', 'Monte Rosa WalserWaeg by UTMB - Walserwaeg Trail', date '2027-07-17', 'Gressoney-Saint-Jean, Italy', 43, 3100, 'https://mrww.utmb.world/races/WWT', 'solo'),
  ('eiger', 6256, 'eiger-ultra-trail-by-utmb-e16-pleasure-trail-2027-utmb-6256', 'Eiger Ultra Trail® by UTMB - E16 - Pleasure Trail', date '2027-07-17', 'Grindelwald, Switzerland', 16, 950, 'https://eiger.utmb.world/races/E16', 'solo'),
  ('eiger', 4051, 'eiger-ultra-trail-by-utmb-e35-north-face-trail-2027-utmb-4051', 'Eiger Ultra Trail® by UTMB - E35 - North Face Trail', date '2027-07-17', 'Burglauenen, Switzerland', 35, 2500, 'https://eiger.utmb.world/races/E35', 'solo'),
  ('eiger', 3970, 'eiger-ultra-trail-by-utmb-e101-ultra-trail-2027-utmb-3970', 'Eiger Ultra Trail® by UTMB - E101 - Ultra Trail', date '2027-07-17', 'Grindelwald, Switzerland', 101, 6700, 'https://eiger.utmb.world/races/E101', 'solo'),
  ('eiger', 1568, 'eiger-ultra-trail-by-utmb-e51-panorama-trail-2027-utmb-1568', 'Eiger Ultra Trail® by UTMB - E51 - Panorama Trail', date '2027-07-17', 'Grindelwald, Switzerland', 51, 3100, 'https://eiger.utmb.world/races/E51', 'solo'),
  ('mrww', 61360, 'monte-rosa-walserwaeg-by-utmb-junior-walser-trail-2027-utmb-61360', 'Monte Rosa WalserWaeg by UTMB - Junior Walser Trail', date '2027-07-18', 'Gressoney-La-Trinité, Italy', 9, 600, 'https://mrww.utmb.world/races/JWT', 'solo'),
  ('mrww', 31230, 'monte-rosa-walserwaeg-by-utmb-regina-margherita-trail-2027-utmb-31230', 'Monte Rosa WalserWaeg by UTMB - Regina Margherita Trail', date '2027-07-18', 'Gressoney-Saint-Jean, Italy', 15, 650, 'https://mrww.utmb.world/races/RMT', 'solo'),
  ('kat', 15763, 'kat100-by-utmb-100-miles-2027-utmb-15763', 'KAT100 by UTMB® - 100 Miles', date '2027-08-05', 'Fieberbrunn, Austria', 169, 9000, 'https://kat.utmb.world/races/100-miles', 'solo'),
  ('kat', 20267, 'kat100-by-utmb-endurance-trail-2027-utmb-20267', 'KAT100 by UTMB® - Endurance Trail', date '2027-08-06', 'Kitzbühel, Austria', 75, 4100, 'https://kat.utmb.world/races/endurance-trail', 'solo'),
  ('kat', 15759, 'kat100-by-utmb-marathon-trail-2027-utmb-15759', 'KAT100 by UTMB® - Marathon Trail', date '2027-08-06', 'Fieberbrunn, Austria', 52, 3100, 'https://kat.utmb.world/races/marathon-trail', 'solo'),
  ('gauja', 55500, 'gauja-trail-by-utmb-gauja-trail-20-k-2027-utmb-55500', 'Gauja Trail by UTMB - Gauja Trail 20 K', date '2027-08-07', 'Cesis, Latvia', 21, 500, 'https://gauja.utmb.world/races/20K', 'solo'),
  ('gauja', 55496, 'gauja-trail-by-utmb-gauja-trail-100-k-2027-utmb-55496', 'Gauja Trail by UTMB - Gauja Trail 100 K', date '2027-08-07', 'Sigulda, Latvia', 91, 2200, 'https://gauja.utmb.world/races/100K', 'solo'),
  ('kat', 43084, 'kat100-by-utmb-easy-trail-2027-utmb-43084', 'KAT100 by UTMB® - Easy Trail', date '2027-08-07', 'Fieberbrunn, Austria', 8, 250, 'https://kat.utmb.world/races/easy-trail', 'solo'),
  ('kat', 15761, 'kat100-by-utmb-speed-trail-2027-utmb-15761', 'KAT100 by UTMB® - Speed Trail', date '2027-08-07', 'Fieberbrunn, Austria', 24, 1650, 'https://kat.utmb.world/races/speed-trail', 'solo'),
  ('gauja', 55504, 'gauja-trail-by-utmb-gauja-trail-10-k-2027-utmb-55504', 'Gauja Trail by UTMB - Gauja Trail 10 K', date '2027-08-08', 'Cesis, Latvia', 13.5, 300, 'https://gauja.utmb.world/races/10K', 'solo'),
  ('gauja', 55498, 'gauja-trail-by-utmb-gauja-trail-50-k-2027-utmb-55498', 'Gauja Trail by UTMB - Gauja Trail 50 K', date '2027-08-08', 'Ratnieki, Latvia', 53, 1200, 'https://gauja.utmb.world/races/50K', 'solo'),
  ('montblanc', 51108, 'hoka-utmb-mont-blanc-occ-2027-utmb-51108', 'HOKA UTMB Mont-Blanc - OCC', date '2027-08-26', 'Chamonix Mont-Blanc, France', 57, 3500, 'https://montblanc.utmb.world/races', 'solo'),
  ('montblanc', 51106, 'hoka-utmb-mont-blanc-ccc-2027-utmb-51106', 'HOKA UTMB Mont-Blanc - CCC', date '2027-08-27', 'Chamonix Mont-Blanc, France', 101, 6050, 'https://montblanc.utmb.world/races', 'solo'),
  ('montblanc', 51104, 'hoka-utmb-mont-blanc-utmb-2027-utmb-51104', 'HOKA UTMB Mont-Blanc - UTMB', date '2027-08-27', 'Chamonix Mont-Blanc, France', 176, 9900, 'https://montblanc.utmb.world/races', 'solo');

do $$
declare source record; event_row public.race_events%rowtype; edition_id_value uuid; target_id uuid;
begin
  for source in select * from _utmb_races order by race_date, utmb_race_id loop
    select * into strict event_row from public.race_events
    where organizer_details #>> '{catalogSource,utmbTenant}' = source.event_tenant;
    select id into strict edition_id_value from public.race_event_editions
    where event_id = event_row.id and edition_year = extract(year from source.race_date)::smallint;

    select race.id into target_id
    from public.races race
    where race.event_id = event_row.id
      and extract(year from coalesce(race.race_date, source.race_date)) = extract(year from source.race_date)
      and (
        race.organizer_details #>> '{catalogSource,utmbRaceId}' = source.utmb_race_id::text
        or (
          race.organizer_details #>> '{catalogSource,utmbRaceId}' is null
          and (
            (
              lower(coalesce(race.source_url, '')) = lower(source.source_url)
              and 1 = (select count(*) from _utmb_races source_sibling
                where source_sibling.event_tenant = source.event_tenant
                  and lower(source_sibling.source_url) = lower(source.source_url))
            )
            or (
              abs(coalesce(race.distance_km, -100000) - source.distance_km) <= greatest(0.5, source.distance_km * 0.02)
              and 1 = (select count(*) from _utmb_races source_sibling
                where source_sibling.event_tenant = source.event_tenant
                  and abs(source_sibling.distance_km - source.distance_km) <= greatest(0.5, source.distance_km * 0.02))
              and 1 = (select count(*) from public.races sibling
                where sibling.event_id = event_row.id
                  and extract(year from coalesce(sibling.race_date, source.race_date)) = extract(year from source.race_date)
                  and sibling.organizer_details #>> '{catalogSource,utmbRaceId}' is null
                  and abs(coalesce(sibling.distance_km, -100000) - source.distance_km) <= greatest(0.5, source.distance_km * 0.02))
            )
          )
        )
      )
    order by case
      when race.organizer_details #>> '{catalogSource,utmbRaceId}' = source.utmb_race_id::text then 0
      when lower(coalesce(race.source_url, '')) = lower(source.source_url) then 1
      else 2 end
    limit 1;

    if target_id is null then
      insert into public.races (
        slug, name, location, location_text, distance_km, elevation_gain_m,
        source_url, external_site_url, is_published, is_live, race_date,
        is_public, has_aid_stations, event_id, edition_group_id, series_name,
        edition_id, racebook_is_live, data_status, missing_required_fields,
        participation_mode, organizer_details
      ) values (
        source.slug, source.name, source.location, source.location, source.distance_km, source.elevation_gain_m,
        source.source_url, source.source_url, true, true, source.race_date,
        true, false, event_row.id, gen_random_uuid(), source.name,
        edition_id_value, false, 'complete', array[]::text[], source.participation_mode,
        jsonb_build_object('catalogSource', jsonb_build_object('kind', 'official', 'provider', 'utmb',
          'utmbRaceId', source.utmb_race_id::text, 'verifiedAt', '2026-09-10'))
      );
    else
      update public.races
      set race_date = source.race_date, location = source.location, location_text = source.location,
          source_url = source.source_url, external_site_url = source.source_url,
          edition_id = edition_id_value, is_published = true, is_live = true, is_public = true,
          data_status = 'complete', missing_required_fields = array[]::text[],
          participation_mode = source.participation_mode,
          organizer_details = coalesce(organizer_details, '{}'::jsonb) || jsonb_build_object(
            'catalogSource', jsonb_build_object('kind', 'official', 'provider', 'utmb',
              'utmbRaceId', source.utmb_race_id::text, 'verifiedAt', '2026-09-10')),
          updated_at = now()
      where id = target_id;
    end if;
  end loop;
end $$;

-- Tighten the temporary compatibility envelope after format dates have been
-- refreshed, while retaining any pre-existing unmatched format in the edition.
update public.race_event_editions edition
set start_date = least(
      source.start_date,
      coalesce((select min(race.race_date) from public.races race where race.edition_id = edition.id), source.start_date)
    ),
    end_date = greatest(
      source.end_date,
      coalesce((select max(race.race_date) from public.races race where race.edition_id = edition.id), source.end_date)
    )
from _utmb_events source
join public.race_events event
  on event.organizer_details #>> '{catalogSource,utmbTenant}' = source.tenant
where edition.event_id = event.id
  and edition.edition_year = extract(year from source.start_date)::smallint;

do $$
declare imported_count integer;
begin
  select count(*) into imported_count
  from public.races
  where organizer_details #>> '{catalogSource,provider}' = 'utmb'
    and organizer_details #>> '{catalogSource,utmbRaceId}' in (select utmb_race_id::text from _utmb_races)
    and is_live and is_public and data_status = 'complete';
  if imported_count <> (select count(*) from _utmb_races) then
    raise exception 'Expected % verified UTMB formats, found %', (select count(*) from _utmb_races), imported_count;
  end if;
end $$;

commit;
